### ISSUE TITLE
wrk not found in path

### ISSUE THREAD

**Issue by anthonybrown** [wg/wrk#103]
followed the wiki and got the same output as shown on the page. when I run    
`wrk 'http:localhost:7777/' -d 3 -c 50 -t 7`
I'm getting the error:
`zsh: command not found: wrk`

**Comment by netpoetica** [comment]
After you run `make`, `wrk` will be in the root of this repo as an executable - at that point, you can run it like so, from the root directory:

```
wrk -d 3 -c 50 -t 7 http://localhost:7777
```

if you want it in your path, you can symlink it with the `ln` command into somethign like /usr/local/bin - hope that helps!

**Comment by FrankLiu2** [comment]
you can try `./wrk`
