### ISSUE TITLE
Request - Response log file

### ISSUE THREAD

**Issue by manikantag** [wg/wrk#106]
It would be very helpful to have an option for logging the request & response into a log file is very helpful, so that we can analyse what server is returning under high load instead of just the error summary. 

Any way we can do this already? Thanks.

**Comment by wg** [comment]
Hi, the [next](https://github.com/wg/wrk/tree/next) branch of wrk now provides some clarification about the scripting implementation, see details in [SCRIPTING](https://github.com/wg/wrk/blob/next/SCRIPTING) and the new [setup example script](https://github.com/wg/wrk/blob/next/scripts/setup.lua) which shows how each thread can maintain a count of requests & responses and print that out when `done()` is called.
