### ISSUE TITLE
support for setting request rate and testing overload behavior

### ISSUE THREAD

**Issue by godmar** [wg/wrk#109]
This is perhaps more of a question than an issue.

Does wrk support fixing a request rate, and if not, is this something you have considered?

As is, wrk entertains a number of concurrent connections, and sends back-to-back requests on those connections. A new request isn't sent until a response has been received. As such, it is not possible to subject a server to a request rate that would exceed its capacity - as the server nears capacity, the latency for each response will increase, which in turn means that wrk will back off and send the next request later. Of course, real-world clients do not exhibit the same behavior - they don't back off as the server nears capacity.

The following papers provide more details; see Banga & Druschel who first recognized the issue and Mosberger & Jin who refer to it in their work on httperf:

http://www.hpl.hp.com/research/linux/httperf/wisp98/httperf.pdf
https://www.usenix.org/legacy/publications/library/proceedings/usits97/full_papers/banga/banga.pdf

httperf, however, does not (appear) to work reliably, especially when attempting to generate overloads in a range where it needs to use --hog to use not just ephemeral ports. At least that's my experience with version 0.9.0 from 2009.

Have you considered extending wrk to be able to generate overload request rates that exceed a server's capacity, or is this not something you deem important, in your professional experience as someone who has worked on a number of highly scalable server infrastructures? How do you test for overload behavior? Thank you for any insights.

**Comment by wg** [comment]
@giltene has a constant-rate fork of wrk at https://github.com/giltene/wrk2.

That's a pretty significant change from how wrk currently works, a user would need to manually run benchmarks at different rates to find the breaking point. In the short term I don't plan such a radical change to wrk.
