### ISSUE TITLE
Make building of luajit optional

### ISSUE THREAD

**Issue by vincentbernat** [wg/wrk#110]
Hi!

To be able to package wrk in most distributions, it should be possible to compile with luajit from the system instead of the embedded copy. If you are not opposed to this, I can propose a modification to the Makefile to make the use of the embedded luajit optional.

**Comment by wg** [comment]
Hi @vincentbernat, thanks for the suggestion! LuaJIT is an integral part of wrk and I want to retain freedom to embed whichever version makes sense for wrk, which may not match the system version.

**Comment by vincentbernat** [comment]
Not being able to use LuaJIT from the system prevents wrk to be packaged in most distributions like Debian, Ubuntu, Fedora. Ability to use the system version doesn't mean you have to support any LuaJIT version.

**Comment by lilydjwg** [comment]
I'd like wrk can be used with system luajit too (I hate the build process to compile what I've already have; the compiling time of luajit is much longer than wrk itself). If you want to use a specific version of luajit, declare as so and packagers will make it right.
