### ISSUE TITLE
why wrk request all fail

### ISSUE THREAD

**Issue by xinghua** [wg/wrk#112]
hello:

 wrk result is

      8 threads and 500 connections
     Thread Stats   Avg      Stdev     Max   +/- Stdev
      Latency     0.00us    0.00us   0.00us    -nan%
      Req/Sec     0.00      0.00     0.00      -nan%
      Latency Distribution
      50%    0.00us
      75%    0.00us
      90%    0.00us
      99%    0.00us
      0 requests in 6.00s, 0.00B read
      Socket errors: connect 0, read 50, write 0, timeout 1177
      Requests/sec:      0.00
      Transfer/sec:       0.00B

but in access log, most of reposne code is 200. the request  http method is PUT, the response header is

    HTTP/1.1 200 OK
    Server: nginx/1.4.1
    Date: Fri, 12 Dec 2014 02:45:00 GMT
    Content-Type: text/html; charset=utf-8
    Content-Length: 0
    Connection: keep-alive
    Cache-Control: no-cache
    "Connection: close"

when I use other benchmark tool such like ab，everything is fine.  In wrk result, I guess the "timeout 1177" are caused by the special calculate method， but why all date report is zero, caused by Content-length 0  or PUT method or others reasons? by the way, i use the script lua like this

    -- put.lua
    wrk.method = "PUT"
    wrk.body   = string.rep("a", 1024)
 

best regards

**Comment by omerzimp** [comment]
I get the same result. Any idea why?

**Comment by omerzimp** [comment]
The problem is with subdomains. If you don't use one wrk will work correctly.

```
./wrk 'https://api.github.com' -c 1 -t 1 -d 5s --latency --timeout 10s
1Running 5s test @ https://api.github.com
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.00us    0.00us   0.00us    -nan%
    Req/Sec     0.00      0.00     0.00      -nan%
  Latency Distribution
     50%    0.00us
     75%    0.00us
     90%    0.00us
     99%    0.00us
  0 requests in 6.01s, 3.25KB read
  Socket errors: connect 0, read 11, write 0, timeout 0
Requests/sec:      0.00
Transfer/sec:     554.46B
```

@wg Got an idea how to resolve this?

**Comment by wg** [comment]
@omerzimp the issue isn't with subdomains, it's that api.github.com requires a User-Agent header and wrk doesn't send one by default. You'll need to add -H "User-Agent: wrk" to the command line. I suspect the errors are due to the response containing content but no Content-Length or Transfer-Encoding.

@xinghua your issue appears to be that the HTTP response is invalid, specifically the Connection header is quoted.

**Comment by omerzimp** [comment]
@wg I'm still getting errors on my own api.
How do I debug this?

**Comment by wg** [comment]
@omerzimp try capturing the HTTP traffic with tcpdump in ASCII mode (with -A).
