### ISSUE TITLE
start timestamp for latency after first write

### ISSUE THREAD

**Issue by ceeaspb** [wg/wrk#115]
For high frequency, low latency servers under test the first socket write could be a significant proportion of the latency.

currently the start of the latency measurement is after the first write. looks like this is incorrect?
this diff (from here : https://github.com/ceeaspb/wrk/commit/48586078976348cd668a1848b993bec544779d69 ) shows the start being moved from after to before the first write

```
@@ -478,17 +500,17 @@ static void socket_writeable(aeEventLoop *loop, int fd, void *data, int mask) {
     size_t len = c->length  - c->written;
     size_t n;
 
+    if (!c->written) {
+        c->start = time_us();
+        c->pending = cfg.pipeline;
+    }
+
     switch (sock.write(c, buf, len, &n)) {
         case OK:    break;
         case ERROR: goto error;
         case RETRY: return;
     }
 
-    if (!c->written) {
-        c->start = time_us();
-        c->pending = cfg.pipeline;
-    }
-
     c->written += n;
     if (c->written == c->length) {
         c->written = 0;
```

this plus the loop_admin change (other ticket) brings the N value from (X*R) up to around 0.989 (aiming for 1).

**Comment by wg** [comment]
Thanks for the suggestion, including the write() time does sound like the correct approach to get accurate latency measurements. I've pushed a commit that does so.
