### ISSUE TITLE
Requests count incorrect

### ISSUE THREAD

**Issue by Berbe** [wg/wrk#119]
Running wrk, the requests count does not seem to be right:

    $ ./wrk -t 4 -d 10 -c 1000 http://127.0.0.1:8080/nop.gif                                        Running 10s test @ http://127.0.0.1:8080/nop.gif
      4 threads and 1000 connections
      Thread Stats   Avg      Stdev     Max   +/- Stdev
        Latency     7.39ms    8.55ms  40.71ms   83.29%
        Req/Sec    54.91k    41.58k  133.11k    70.67%
      1775704 requests in 10.00s, 397.96MB read
    Requests/sec: 177583.42
    Transfer/sec:     39.80MB
    $ awk -F '"' '{split($11, field, " "); print $2" "field[1]}' /var/log/nginx/access.bench.log | uniq -c
    1776576 GET /nop.gif HTTP/1.1 200
The `access.bench.log` file has been flushed (ie deleted and reopened) right before the test was run.

Purely informational: The fields from the log I display are the requested method/URI/protocol version, associated with the HTTP response code.

**Comment by wg** [comment]
Hi @Berbe, wrk runs a calibration phase first to determine the expected response rate and sampling interval. This involves making some number of requests, but wrk's output only includes results from after calibration is complete and the real test starts.
