### ISSUE TITLE
Feature Request: Provide support for not caching the domain name

### ISSUE THREAD

**Issue by jcw9930** [wg/wrk#120]
It would be nice to have support for not caching the domain name. While it is useful for most scenarios, for region failover test based on DNS this is not desired. Currently wrk doesn't support this and when the IPs change behind the domain, wrk will continue to hit the old ones.

**Comment by wg** [comment]
Hi @jcw9930, check out the 'next' branch at https://glozer.net/src/wrk.git. It has many scripting improvements including support for doing address resolution in Lua and assigning one of the resolved addresses to the threads.

**Comment by jcw9930** [comment]
Thanks! However I seem to be unable to clone the repo:

$ LANG=C git clone -v https://glozer.net/src/wrk.git
Cloning into 'wrk'...
fatal: unable to access 'https://glozer.net/src/wrk.git/': Cannot communicate securely with peer: no common encryption algorithm(s).

**Comment by wg** [comment]
Your copy of git might be linked with an old version of OpenSSL, try plain http://
