### ISSUE TITLE
Execute other HTTP requests before/after the benchmarked one?

### ISSUE THREAD

**Issue by zserge** [wg/wrk#122]
I know it's not a common benchmarking use case, but let's imagine that I want to benchmark some DELETE request that removes a certain object from the collection. To run this request the object should be created first using some POST request.

I wonder if I can use Lua scripting to execute that "POST /myobjects" request and then run (and benchmark) the "DELETE /myobjects/123" request, where 123 is the ID received from the POST response.

I know that I can use the request/response callbacks, but in this case I assume both POST and DELETE will be measured, right? Is there any way to exclude a certain request from the measurements or run custom not benchmarked requests in between?

**Comment by wg** [comment]
Hi @zserge, there's no way to do this today. You're correct that both the POST and DELETE requests would be measured. One alternative might be to do the POST in a background thread on the server, after the DELETE returns a response.
