### ISSUE TITLE
cd bug in the Makefile

### ISSUE THREAD

**Issue by ajstarks** [wg/wrk#128]
When building on Mac OS X 10.10.3, I had to the Makefile to use this line:

    LDIR     = ./deps/luajit/src

otherwise the build failed

**Comment by wg** [comment]
Hi @ajstarks, I can't reproduce this issue on 10.10.3. Did you clone directly from github and attempt to build from the repo root? What version of make are you using?

**Comment by ajstarks** [comment]
I just cloned from github. and typed "make".  By the way, nice tool (I'm using it to test an image web service)

**Comment by fatso83** [comment]
@ajstarks you realize you never answered the question on what version of make you were running? 

`make -v`

**Comment by wg** [comment]
I haven't been able to reproduce this but have refactored the Makefile.
