### ISSUE TITLE
Install issue on Ubuntu 14.x

### ISSUE THREAD

**Issue by updatus** [wg/wrk#129]
OK        Successfully built LuaJIT
make[1]: Leaving directory `/home/vadim/wrk/wrk/deps/luajit/src'
CC src/wrk.c
In file included from src/wrk.c:3:0:
src/wrk.h:11:25: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
                         ^
compilation terminated.
make: *** [obj/wrk.o] Error 1

**Comment by updatus** [comment]
I have installed it. The issue was with 'openssl-devel' package which is called 'libssl-dev' under Ubuntu.
apt-get install libssl-dev. This one can be closed.

**Comment by fidiego** [comment]
Thanks @updatus 

this came in clutch when installing wrk on a docker image (`FROM python:3.6-slim`)
