### ISSUE TITLE
setup.lua script broken

### ISSUE THREAD

**Issue by danvk** [wg/wrk#130]
When I try to use [`scripts/setup.lua`][1], I get the following error:

    $ wrk -s setup.lua http://www.google.com/
    PANIC: unprotected error in call to Lua API (setup.lua:19: bad argument #1 to 'format' (number expected, got nil))

The error is on the `print` call in `init`:

```lua
function init(args)
   requests  = 0
   responses = 0

   local msg = "thread %d created"
   print(msg:format(id))
end
```

i.e. it seems like the call to `thread:set("id", counter)` is not behaving in the expected way.

[1]: https://github.com/wg/wrk/blob/a20969192f7bc095ad3ad3e238a9a581e64ae4f9/scripts/setup.lua

**Comment by wg** [comment]
Hi @danvk, I can't replicate this issue locally. What OS are you running wrk on, and can you reply with the first line of output from `wrk --version`? Are you running with a clean checkout & build?

**Comment by danvk** [comment]
```
$ wrk --version
wrk 3.1.1
```

I'm on Mac OS X. I installed `wrk` using `brew install wrk`. It looks like the brew formula is a few versions behind.

**Comment by methane** [comment]
brew has wrk4.0.1 formula

2015年4月27日月曜日、Dan Vanderkam<notifications@github.com>さんは書きました:

> $ wrk --version
> wrk 3.1.1
>
> I'm on Mac OS X. I installed wrk using brew install wrk. It looks like
> the brew formula is a few versions behind.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wg/wrk/issues/130#issuecomment-96660448>.
>


-- 
INADA Naoki  <songofacandy@gmail.com>

**Comment by danvk** [comment]
A simple `brew update` did the trick, and this script does indeed work with `wrk` 4.0. Sorry for the false alarm!

**Comment by wg** [comment]
@danvk glad it's working, thanks for chiming in @methane!
