### ISSUE TITLE
Fixed load for long period ?

### ISSUE THREAD

**Issue by Prots** [wg/wrk#131]
Hi guys, how I can run wrk with fixed load, for example 300 requests per second? 
It is a nice tool for stress test, but now I need something for modeling a real load with some average req/sec. Could you please help with that? Thanks!

**Comment by wg** [comment]
Hi @Prots, wrk doesn't support fixed rate testing. You might try httperf or [vegeta](https://github.com/tsenart/vegeta) depending on what sort of performance you need.
