### ISSUE TITLE
When returning a table in request() only the top 100 requests are used

### ISSUE THREAD

**Issue by JelteF** [wg/wrk#132]
I'm trying to get a pipeline script like this one working https://github.com/wg/wrk/blob/master/scripts/pipeline.lua

But it seems only the first 100 elements are being used and I need all the requests to be issued at one point. I am now using a workaround of looping over the table myself and returning one element at a time, but it seems like something that should be fixed in the application itself. 

I wouldn't mind fixing it myself if necessary, could you maybe point me in the right direction?

**Comment by wg** [comment]
Hi @JelteF, the `request()` function needs to return a string, not a table. pipeline.lua demonstrates sending 3 simultaneous requests before waiting for the first response, AKA HTTP pipelining. Are you wanting something else?

**Comment by JelteF** [comment]
Sorry to respond so late. What I means was if you concat a table like that with more than 100 entries, only the first 100 are used.

**Comment by wg** [comment]
I tested a pipeline of > 100 requests when you first opened this issue and it worked fine with nginx. What HTTP server are you testing against? I guess it's possible yours doesn't support that depth, is a bit unreasonable after all.

**Comment by JelteF** [comment]
Ah ok, I now understand better what you mean. I did use Nginx as well btw, but possibly an older version.  In that case this is indeed not an issue with wrk.
