### ISSUE TITLE
Headers not available in lua response function

### ISSUE THREAD

**Issue by czerasz** [wg/wrk#133]
The `headers` variable is empty in the `response` function.

    response = function (status, headers, body)

Use this [repo](https://github.com/czerasz/wrk-debugging-environment) to reproduce.

The application in the example returns an `X-Debug: true` header but the `headers` table in is empty.

**Comment by wg** [comment]
Hi @czerasz, `headers` is a table with string keys so you can't use the length operator (`#headers`) or `ipairs`. Try with `pairs` instead.

**Comment by czerasz** [comment]
Thanks a lot for the fast feedback! This led me show all the response headers.
