### ISSUE TITLE
How to use the response inside of done lua function

### ISSUE THREAD

**Issue by czerasz** [wg/wrk#134]
According to the [scripting documentation](https://github.com/wg/wrk/blob/0f8016c907a7fdebde2e670489057681c73a09aa/SCRIPTING#L92), inside the `done` function a `requests` variable is available:

    function done(summary, latency, requests)

What does this variable contain and how to use it to get valuable data?

**Comment by wg** [comment]
@czerasz the `latency` and `requests` parameters to `done` are both statistics objects accessible as described in the docs and `requests` contains the per-thread request rate statistics.

**Comment by czerasz** [comment]
Does the `request` object contain any methods like the `latency` (`latency:percentile`)?

When I debug the `request` inside my [debugging environment](https://github.com/czerasz/wrk-debugging-environment) with this Lua code:

    io.write("------------------------------\n")
    var_dump(requests(0))
    io.write("------------------------------\n")
    var_dump(requests(1))
    io.write("------------------------------\n")
    var_dump(requests(2))
    io.write("------------------------------\n")
    var_dump(requests(3))
    io.write("------------------------------\n")
    var_dump(requests(4))
    io.write("------------------------------\n")
    var_dump(requests(5))
    io.write("------------------------------\n")

I get this:

    ------------------------------
    {
      [1] = "0", 
      [2] = "20"
    }
    ------------------------------
    {
      [1] = "1240", 
      [2] = "1"
    }
    ------------------------------
    {
      [1] = "1252", 
      [2] = "1"
    }
    ------------------------------
    {
      [1] = "1340", 
      [2] = "1"
    }
    ------------------------------
    {
      [1] = "1370", 
      [2] = "1"
    }
    ------------------------------
    {
      [1] = "1390", 
      [2] = "1"
    }
    ------------------------------

How to interpret this data?

The first result (`[1] = "0", [2] = "20"`) seems to be different then the other ones (`[1] = "1240", [2] = "1"`).

I use this command to generate it:

    wrk -c3 -d1s -t2 -s /scripts/debug.lua http://app:3000 -- debug true

**Comment by wg** [comment]
Yup, `requests` and `latency` have exactly the same methods. Treating them as callable returns the raw value and number of occurrences of that value. That's useful if you want more detailed stats but generally you'd just want to use the summary methods min, max, percentile, etc.
