### ISSUE TITLE
How to assign ip address?

### ISSUE THREAD

**Issue by nkrode** [wg/wrk#137]
I'm trying to dynamically set the server ip address using the example script below. However I get an error 
"PANIC: unprotected error in call to Lua API (address.lua:14: bad argument #4 to '__newindex' (wrk.addr expected, got string))'

What is the format to assign the ip to addrs variable?

```
local addrs = {}
addrs[1]="192.168.1.1:80"

function setup(thread)
   if not addrs then
      addrs = wrk.lookup(wrk.host, wrk.port or "http")
      for i = #addrs, 1, -1 do
         if not wrk.connect(addrs[i]) then
            table.remove(addrs, i)
         end
      end
   end

   thread.addr = addrs[math.random(#addrs)]
end

function init(args)
   local msg = "thread addr: %s"
   print(msg:format(wrk.thread.addr))
end

```

**Comment by wg** [comment]
Hi @nkrode, you need to use `wrk.lookup` to resolve the IP and port. That method returns a table of wrk.addrs which you can assign to `thread.addr`.

**Comment by nkrode** [comment]
Hi Thanks for your quick reply, I tried adding using wrk.lookup but I doesn't seem to work. Can you show me a quick example of how I can add multiple servers to the array. Thanks!

```
local addrs = { wrk.lookup("192.168.1.1","8100"),  wrk.lookup("192.168.1.1","8200") }
```

**Comment by wg** [comment]
`wrk.lookup` returns a table, so you're creating a table of tables of wrk.addrs which won't work. As a quick hack you could just get the first item from each wrk.lookup call, e.g:

```lua
local addrs = { wrk.lookup("192.168.1.1","8100")[1], wrk.lookup("192.168.1.1","8200")[1] }`

But it'd be better to do what the sample code in addr.lua does and check each address returned to make sure it's connectable.

**Comment by nkrode** [comment]
Does  thread.addr set the target host IP or does it set the local thread's ip? Not sure if I should set thread.addr or wrk.host in the global table ? I want to randomly change the host address for the GET request.

**Comment by wg** [comment]
Do you want to change the IP address that wrk connects to, or the `Host:` HTTP header? Setting thread.addr does the former and wrk.host the later, although if you want to repeatedly change the header during a benchmark you should implement the `request()` function and call `wrk.format()`.

**Comment by nkrode** [comment]
I have 2 webservers, 192.168.1.1 and 192.168.1.2, I want to run an HTTP benchmark against both the servers combined, I want to figure out what is the QPSs both these can do combined. Instead of manually testing each one at a time and adding up the results, I want both to be tested in a single test.

I want to setup a lua script which changes the requested URL including the host name being connected to.
./wrk "http://192.168.1.1" 
./wrk "http://192.168.1.2"

I tried to use the following lua script, with the command line omitting specifying the URL, but it doesn't work. If I specify the url in the command line then it seems the wrk.host property is ignored:  

```
./wrk -t12 -c150 -d10s -s script.lua
```

```
request = function()
   wrk.host = "192.168.1.1"
   wrk.scheme = "http"
   wrk.port = 8100
   return wrk.format("GET","/ping",nil,nil)
end
```

**Comment by wg** [comment]
The URL command line argument is required, even if you override the destination address in the Lua script. This is probably how I'd do what you're asking for:

```lua
local addrs   = {}
local counter = 0

function setup(thread)
   local append = function(host, port)
      for i, addr in ipairs(wrk.lookup(host, port)) do
         if wrk.connect(addr) then
            addrs[#addrs+1] = addr
         end
      end
   end

   if #addrs == 0 then
      append("192.168.1.1", 80)
      append("192.168.1.2", 80)
   end

   local index = counter % #addrs + 1
   counter = counter + 1
   thread.addr = addrs[index]
end
```

**Comment by amsharma** [comment]
Am trying to use the above suggestion. But keep getting the below error.

PANIC: unprotected error in call to Lua API (scripts/final-addr.lua:20: attempt to call field 'append' (a nil value))

**Comment by Fatahir** [comment]
@nkrode  did you find latency of each address? If yes then how?

**Comment by Fatahir** [comment]
i want to change each thread address in setup function so that my 2 threads run test different urls. My setup function is 
`function setup(thread)

	print("thread:", counter)
	thread:set("id", counter)
   	if counter==0 then 
		thread.addr= "http://localhost:8080"
	else 
		thread.addr= "http://localhost:8080/compose.html"
	end
end`

it generates error **unprotected error in call to Lua API (./f.lua:25: bad argument #4 to '__newindex' (wrk.addr expected, got string))**
help me to solve this issue. what i want is [this](https://github.com/giltene/wrk2/issues/93)
