### ISSUE TITLE
Proper way to pass multiple values in body

### ISSUE THREAD

**Issue by Naughtron** [wg/wrk#138]
Good day, 

I have a quick question related to passing multiple values in a POST body using wrk. In this script I am making a POST to an endpoint that takes in a JSON payload with a number of key : value pairs. 

I just wanted a second set of eyes on the script to make sure I am passing things correctly. 

Thank you for your time. 

./Chris 

-- Command Line:
--./wrk -t2 -c2 -d10s -s <pathToScript>

random = tostring(os.clock())

wrk.method = "POST"
wrk.headers["authorization"] = "<authTokenHere>"
wrk.body = "{\"name\":\"testAccountUser\" .. random,
             \"entityId\":\"testEntityId\" .. random,
             \"entityType\":\"entityType\" .. random,
             \"accountId\":\"accountId\" .. random,
             \"persistenceType\":\"simple\" .. random
            }"

done = function(summary, latency, requests)
   io.write("------------------------------\n")
   for _, p in pairs({ 50, 90, 99, 99.999 }) do
      n = latency:percentile(p)
      io.write(string.format("%g%%,%d\n", p, n))
   end
end

**Comment by wg** [comment]
Hi @Naughtron, this looks fine to me but it really depends on what your endpoint is expecting. JSON is a good approach. You might also consider using a Lua JSON library to generate the JSON, might be more readable than building by hand.

**Comment by Naughtron** [comment]
Thank you very much @wg I appreciate the help.
