### ISSUE TITLE
Allow self-signed SSL certs

### ISSUE THREAD

**Issue by tarndt** [wg/wrk#139]
It would be great if wrk supported something like curl's "-k, --insecure" so that it could be used to test HTTPs origins with self-signed certs.

**Comment by wg** [comment]
Hi @tarndt, wrk already configures OpenSSL to ignore cert verification results so self-signed certs should work fine. Are you finding they don't?

**Comment by tarndt** [comment]
@wg Sorry, it turned out I was misinterpreting another error that was taking place.

**Comment by knasim** [comment]
@wg what do i need to pass into wrk args to accomplish "--insecure" like with curl.
