### ISSUE TITLE
Reported "requests" against "Socket errors"

### ISSUE THREAD

**Issue by oneumyvakin** [wg/wrk#140]
./wrk -t12 -c100 -d30s --timeout 10s  http://domain.local/test.php
Running 30s test @ http://domain.local/test.php
  12 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.85s     2.75s    9.54s    80.39%
    Req/Sec     1.82      3.58    30.00     91.95%
  **296** requests in 30.10s, 61.57KB read
  Socket errors: connect 0, read 0, write 0, timeout **41**
Requests/sec:      9.83
Transfer/sec:      2.05KB

I've read output as **296** requests was OK, and **41** requests was not OK.
Total: **337**

But in nginx log I've see **300** requests with HTTP 200 and **92** requests with HTTP 499

~# cat access_log | grep "200 29" | wc -l
**300**
~# cat access_log | grep "499 0" | wc -l
**92**
~# cat access_log | grep "test.php" | wc -l
Total: **392**

1. Have I read it right?
2. Why not all actually performed requests are reported?

**Comment by wg** [comment]
Hi @oneumyvakin, what version of wrk are you using? Prior to 4.0.0 wrk had a calibration period which issued requests to determine the sampling rate. All stats collected during calibration were dropped because they'd be inaccurate.

**Comment by oneumyvakin** [comment]
./wrk -v
wrk 4.0.0 [epoll] Copyright (C) 2012 Will Glozer

Thanks, I've got it.
