### ISSUE TITLE
Allow (limited) data sharing between wrk threads

### ISSUE THREAD

**Issue by themoriarty** [wg/wrk#141]
This is not as scary as it sounds :), here's my usecase: 
I have a big static set of requests that are pretty expensive (10 minutes) to compute. Since those requests are read-only, I'd love to pre-compute them once and use in all threads. But there seems to be no way to share them, since each thread uses its own lua environment. 

I'm not sure it's possible to support the generic case, but at least something limited (like sharing only primitives) would be good enough.

**Comment by wg** [comment]
Hi @themoriarty, wrk 4.0.0 added a setup phase which can be used to set globals in each thread's environment. So if you can precompute your request during setup this should be no problem.

**Comment by themoriarty** [comment]
@wg right, but to set something in thread's environment, I have to first compute it.
here's how I check that thread's environment is unique to each thread:
```lua
setup = function(thread)
  print('before set', thread, thread:get('field'))
  thread:set('field', 'value')
  print('after set', thread, thread:get('field'))
end
```
```
wrk --latency -d 10s -t 2 -c 2 -s main3.lua
before set	userdata: 0x0c512298	nil
after set	userdata: 0x0c512298	value
before set	userdata: 0x0c5124e8	nil
after set	userdata: 0x0c5124e8	value
```

And here is how my usecase looks like:
```lua
local _requests
setup = function(thread)
   _requests = really_expensive_computation()
end
```
Now ```really_expensive_computation``` is executed in each thread and there's no way I could re-use the results of the first computation. This is (conceptually) want I'd like to achieve:
```lua
local _requests
setup = function(thread, global_store)
   if not global_store:contains('key') then
     global_store:set('key', really_expensive_computation())
   end
   _requests = global_store:get('key')
end
```

But again, I'm not sure it's possible to share **complex** states between environments.

**Comment by wg** [comment]
I see what you're getting at. The `setup(thread)` function runs in a different environment that persists for each call to `setup()` as well as the call to `done()`. So you can simply do

```lua
local _requests
setup = function(thread)
   if not _requests then
       _requests = really_expensive_computation()
   end
   thread:set("_requests", _requests)
end
```
Of course `_requests` must be a simple type, such as a table of request strings, a table of tables, etc.

**Comment by themoriarty** [comment]
```
themoriarty:~/wrk/$ ./wrk --version
wrk 4.0.0 [kqueue] Copyright (C) 2012 Will Glozer
```
Using this script:
```lua
local _requests
setup = function(thread)
   if not _requests then
      print("creating requests in", thread)
   else
      print("reusing requests in", thread)
   end
   thread:set("_requests", _requests)
end
```
And the output is:
```console
themoriarty:~/wrk/$ ./wrk -d 10s -t 2 -c 2 -s main3.lua http://example.com/
creating requests in	userdata: 0x1528f2f8
creating requests in	userdata: 0x1528f6f0
```

I think I'm either doing something wrong, or it's not possible to do it.

If my reading of ```script_create``` is correct, the first thing it does is ```lua_State *L = luaL_newstate()```, the it loads wrk module, registers a few functions, and finally loads the file. Since ```script_create``` (and luaL_newstate()) is called in each thread, there's no shared date between different lua scripts whatsoever. 
Btw, the workaround I currently have is load all requests to raw memory with ffi (I have 1M+ requests, so ffi is the only option to overcome 1GB luajit memory limit), and that allows me to store the raw pointer in current process' environment variable. This is about the ugliest thing I've done in my entire life.

**Comment by wg** [comment]
Your example code never sets `_requests`, but there's another issue in that `thread:set` sets globals and the first line is creating a local `_requests` for each thread. So you either need to make it a global or use a different name for the thread-local value.

```lua

_requests = nil

function setup(thread)
   if not _requests then
      print("creating requests in", thread)
      _requests = "foo"
   else
      print("reusing requests in", thread)
   end
   thread:set("_requests", _requests)
end

function init(args)
   print("local _requests is", _requests)
end
```

**Comment by themoriarty** [comment]
Oh, I completely misunderstood what thread:set() does. Thanks for the explanation!
