### ISSUE TITLE
Access to total thread count in thread

### ISSUE THREAD

**Issue by ragnard** [wg/wrk#143]
Hi,

First, thanks for an excellent piece of software.

I'm trying to write a script that reads requests from a file into a table, and then replays them. If running with multiple threads, I'd like the requests to be round-robin'd between the threads, so that thread 1 gets requests 1, n+1, (2*n)+1, (3*n)+1, thread 2 request 2, n+2, (2*n)+2, (3*n)+2, etc, where n is the total number of threads.

The ideal way to do this would be to read, parse, prepare and partition everything in `init`, so each thread  has a table of only the requests it should fire and then just run through that table in `request`. However, I have not found a way to discover the total number of threads in `init`.

- Have a missed the obvious way to do this?
- If not, would you consider a PR implementing this?

**Comment by wg** [comment]
Hi @ragnard, the simplest way would be just to pass the number of threads as an extra script parameter, e.g. `wrk -t2 -s script.lua http://localhost -- 2`.

A more efficient & fancier approach would be to use the new setup phase to keep a counter of threads, initialize the requests table once, and pass it and the current thread counter value to each thread similar to https://github.com/wg/wrk/blob/master/scripts/setup.lua

**Comment by ragnard** [comment]
Thanks @wg for the (quick!) reply!

I've tried both options. Passing it as an argument definitely works, but means there's room for error/discrepancy and feels a bit redundant as it's already part of the "global" configuration.

I've also tried to use the `setup` phase (I'm running off master) to keep a counter as you say, but I couldn't get that to work as it seems like, for each thread, `script_init` calls `setup` and `init` in sequence, so only the last thread would have access to the complete table of threads and would thus know the total number of threads. Again, maybe I'm missing something here?

This is what I tried:

```lua
local thread_id_counter = 1
local threads = {}

function setup(thread)
   thread:set("thread_id", thread_id_counter)
   table.insert(threads, thread)
   -- update all known theads with the latest thread count
   for _, t in ipairs(threads) do
      t:set("thread_count", thread_id_counter)
   end
   thread_id_counter = thread_id_counter + 1
end

function init(args)
   print(string.format("thread %d of %d", thread_id, thread_count))
end
``` 

This prints:
```
$ wrk ...
thread 1 of 1
thread 2 of 2
thread 3 of 3
thread 4 of 4
thread 5 of 5
thread 6 of 6
thread 7 of 7
thread 8 of 8
...
```

Also, if I had access to the command line args in `setup`, I could do the parsing etc once for all threads, and then just assign each thread the subset of requests it needed using `thread:set`, then I wouldn't need to do any work in `setup`. Currently I'm doing everything n times.

Really appreciate your help with this, sorry if I'm missing something,

**Comment by ragnard** [comment]
Forget that last part, `setup` is still called once per thread so AFAICT there's now way to do a once-per-benchmark initialization.

**Comment by wg** [comment]
`setup()` is indeed called once per thread, but the Lua context is preserved so you can maintain state outside that function. Just check if that state is already initialized and if not do the initialization.

**Comment by ragnard** [comment]
For my use-case I need to know the total number of threads in order to partition the requests and I don't know that until `setup` runs for the last time (and I can't tell when that occurs). As `init` is executed directly after `setup` in each thread (but in a different Lua context) I still can't know what the total is in that context either.

Also, I take the file to read requests from as a command line argument and I don't have access to that in `setup` so I don't know where to load requests from...

**Comment by wg** [comment]
Ahh I understand, you want the full count in init()? In that case the best approach might be to pass your configuration parameters in environment variables that you read from Lua, and reference on the command line.

**Comment by bjne** [comment]
```lua
local function get_nthreads()
	return (string.match(io.lines('/proc/self/cmdline')(), '-t%D+(%d+)')) or 2
end
```

Sad that this is not exposed to lua
