### ISSUE TITLE
Stop the test from script

### ISSUE THREAD

**Issue by hallucynogenyc** [wg/wrk#144]
Hi, I'm trying to use WRK to identify threading issues in an app. I have a list of endpoints to hit and I want to smash them until either a minute has passed, or a 500 has been received. In the second case, I'd want to print the body of the 500 and immediately stop the test. Is there a way to stop all the threads at once?

**Comment by wg** [comment]
There's no built-in way, but you've got the full power of LuaJIT's FFI available so something like POSIX shared memory might work. Could do a semaphore file too, depending on your performance needs.

**Comment by hallucynogenyc** [comment]
Couldn't I just kill the proces altogether using FFI then?

**Comment by wg** [comment]
Sure, or you could just use `os.exit()`. I was assuming you still wanted the stats output, in which case you could use shared memory to tell each thread when to call `thread:stop()`.
