### ISSUE TITLE
Is there a way to add a body with uuid generated?

### ISSUE THREAD

**Issue by gideonairex** [wg/wrk#146]
I have a POST request where a uuid is from the client side. I want to create a lua script inside the request function but I cant seem to include https://github.com/mah0x211/lua-ossp-uuid. I have installed it using luaRock but cant include it in wrk. I am a newbie to lua so bare with me.

**Comment by wg** [comment]
Hi @gideonairex, wrk contains an embedded LuaJIT so you'd need to build this library against LuaJIT and then load the .so shared library from inside your Lua script. Should be possible theoretically but can't say that I've tried.

**Comment by gideonairex** [comment]
@wg Thanks!

**Comment by nhooey** [comment]
@gideonairex Did you ever figure this out?

**Comment by gideonairex** [comment]
@nhooey what I have remembered is that I was able to make this work. But I moved to a different tool like https://artillery.io/
