### ISSUE TITLE
How did you get over 700k rps?

### ISSUE THREAD

**Issue by adwinsky** [wg/wrk#147]
Using wrk I am benchmarking simple ping - pong http server written in GO. I am using Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz with 32 threads. My web server is using all CPUs available and with the same parameters you used in the Readme example (wrk -t12 -c400 -d30s http://127.0.0.1:8080/index.html) I am not able to get more then 300k rps. I have kernel configured to quickly reuse tcp connections and I have no idea how to get better results. 

Therefore I wanted to ask about your example:

* what machine was used?
* what web server you tested? (with nginx I was not able to get more then 150k rps).
* what is your sysctl configuration.

My assumption is that the bottleneck is the CPU I am using.

I also think it would be nice to add this informations to the Readme page.

**Comment by wg** [comment]
Hi @adwinsky, IIRC those results are from an EC2 c3.8xlarge instance. More recently I tested a c4.8xlarge and saw > 1M requests/sec with nginx 1.6. Should be even better with nginx 1.9 on Linux: https://www.nginx.com/blog/socket-sharding-nginx-release-1-9-1/

Allocating all CPUs to the HTTP server probably means wrk isn't getting enough CPU time. If you're running Linux try running the `perf` tool during a test and see where CPU time is spent.

**Comment by defanator** [comment]
Hi Will,

could you share some details about nginx configuration and payload used to get such numbers on AWS? :)

**Comment by wg** [comment]
Hey @defanator, sure it's a really basic config:

```
worker_processes     24;
worker_rlimit_nofile 262144;

daemon off;

events {
  use epoll;
  worker_connections 16384;
}

error_log error.log;
pid nginx.pid;

http {
  access_log off;
  sendfile   on;
  tcp_nopush on;

  keepalive_requests 100;
  open_file_cache max=100;

  server {
    listen [::]:8080 ipv6only=off reuseport backlog=16384;

    location / {
      root   html;
      index  index.html;
    }
  }
}
```
The default clocksource is the initial bottleneck on EC2 HVM so you need to do `echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource`

```
./wrk -t12 -c400 -d30s http://127.0.0.1:8080/index.html
Running 30s test @ http://127.0.0.1:8080/index.html
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   592.47us    3.19ms 126.50ms   97.55%
    Req/Sec   104.25k     5.42k  139.93k    86.36%
  37427950 requests in 30.10s, 29.59GB read
Requests/sec: 1243449.23
Transfer/sec:      0.98GB
```

For more reliable results you might want to turn off Turbo Boost: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/processor_state_control.html

**Comment by defanator** [comment]
Is nginx compiled from sources or installed with packages? What is the origin of packages, in latter case?

What is the size of the index.html returned?

**Comment by wg** [comment]
Compiled from source, that's the index.html in http://nginx.org/download/nginx-1.9.2.tar.gz

**Comment by methane** [comment]
WoW! Since wrk uses keep-alive, I thought `reuseport` doesn't boost performance.
It's very interesting.

**Comment by wg** [comment]
@methane I haven't actually tested reuseport on and off, on the same system. But with keepalive_requests at 100 there will still be a lot of new connections at this request rate.
