### ISSUE TITLE
how to write a radom reuest?

### ISSUE THREAD

**Issue by zphj1987** [wg/wrk#148]
hello wg :
my nginx URL is.  http://192.168.1.101/download/
and in dir download i put 1000 file like a1 to a1000 ,I want to start a test.  5 thread ,radom Request the file in download dir.    
how to write the Lua script. and the command? thankyou !

**Comment by wg** [comment]
Hi @zphj1987, the example scripts should give you enough hints to accomplish this: https://github.com/wg/wrk/tree/master/scripts
