### ISSUE TITLE
JSON or machine friendly output

### ISSUE THREAD

**Issue by tj** [wg/wrk#15]
as an option would be fantastic. If you're interested I can send a pull-request

**Comment by jar-o** [comment]
well in lieu of a better solution (which doesn't appear forthcoming) you can solve this with the following script which formats a simple, single-line JSON string that you can easily `grep`:

**report_json.lua**

```
done = function(summary, latency, requests)
    io.write("------------------------------ json:\n")
    io.write(string.format(
        "{\"json_output\":{\"requests_sec\":%.2f,\"avg_latency_ms\":%.2f}}",
        summary.requests/(summary.duration/1000000),
        (latency.mean/1000)
        ))
end
```

**Comment by robinpecha** [comment]
Hi, how it works?

wrk url | report_json.lua
./report_json.lua url
