### ISSUE TITLE
Headers at the command line

### ISSUE THREAD

**Issue by Tyguy7** [wg/wrk#153]
I would love to see an example of how to use custom headers at the command line.

```./wrk -H "Authorization:Basic 4525j24k532ktwklt" http://localhost...```

doesn't seem to work.

**Comment by wg** [comment]
Try it with a space after the parameter name and colon.

**Comment by dodekeract** [comment]
For anyone seeing this issue through Google: `-H "Name: Value"` is the correct syntax.

**Comment by rainchen** [comment]
@dodekeract you saved my date. This hints should be added to README

**Comment by gabrie30** [comment]
Is there any way to use multiple headers?

**Comment by cristipufu** [comment]
Yes, `-H "Name1: Value1" -H "Name2: Value2" -H "Name3: Value3"`

**Comment by spawn08** [comment]
hey guys what with be the "Name" and "Value" in the above case?

**Comment by ilolicon** [comment]
```
echo -n 'username:password' | base64
>> base64code

wrk -H "Authorization: Basic base64code" url
```
