### ISSUE TITLE
how to script pipeline.lua?

### ISSUE THREAD

**Issue by cheers00** [wg/wrk#155]
I am trying to understand how to use pipeline script? I am running node.js ```helloworld``` and I am trying to loadtest it with wrk. If I want to pipeline http requests, what should be the script?

```
init = function(args)
   local r = {}
   r[1] = wrk.format(nil, "/?foo")
   r[2] = wrk.format(nil, "/?bar")
   r[3] = wrk.format(nil, "/?baz")

   req = table.concat(r)
end

request = function()
   return req
end
```

**Comment by Tyguy7** [comment]
I'd like to know this as well as how to chain requests.

**Comment by wg** [comment]
Are you asking how to pass a parameter for the number of pipelined requests? If so you'll find an example here: https://github.com/wg/wrk/issues/59#issuecomment-111727388
