### ISSUE TITLE
Won't compile in aarch64 platforms

### ISSUE THREAD

**Issue by LinuxJedi** [wg/wrk#160]
LuaJIT 2.0.4 doesn't support aarch64 and won't compile on that platform.  Support was added in LuaJIT 2.1 but this is still in beta.

I've created a branch for now that has LuaJIT 2.1 and compiles in aarch64 for my own use, but haven't created a pull request because it is still a beta: https://github.com/LinuxJedi/wrk/tree/aarch64_support

**Comment by wg** [comment]
Thanks @LinuxJedi! I'll upgrade wrk to LuaJIT 2.1 as soon as a final version is released.

**Comment by sjtuhjh** [comment]
@wg, have we integrated LuaJIT2.1 yet?　The wrk still could be compiled on ARM64 platform.
