### ISSUE TITLE
is there any possibility to extract response body data (e.g. csrf-token) from a first request(get) and use it in the next one(post) ?

### ISSUE THREAD

**Issue by updatus** [wg/wrk#161]
Basic idea: I want to test some real user login requests:
1. GET request to a server. The response contains csrf-token (in a body).
2. Use this token in a next POST request.
Will be appreciate for any help with extract response data from GET request.

**Comment by wg** [comment]
Sure, check out the [auth.lua](https://github.com/wg/wrk/blob/master/scripts/auth.lua) sample script.

**Comment by updatus** [comment]
Thank you for help.
