### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by povilasb** [wg/wrk#162]
It would be nice if `wrk` supported proxy option.

**Comment by kamiccolo** [comment]
Related feature request: [#6](https://github.com/wg/wrk/issues/6)

**Comment by wg** [comment]
If you mean an HTTP proxy is there any reason you can't use the Lua scripting to generate a proxied request?

**Comment by povilasb** [comment]
This works just fine: `wrk -c 1 -t 1 -d 1 -s via_proxy.lua http://proxy_addr:8080`

via_proxy.lua:

    wrk.path = "http://google.com/"
    wrk.headers["Host"] = "google.com"
    wrk.headers["Proxy-Authorization"] = "Basic dXNlcjE6cGFzc3dvcmQx"
    wrk.headers["Proxy-Connection"] = "Keep-Alive"

But with HTTPS I'm not so lucky. I was trying: `wrk -c 1 -t 1 -d 1 -s via_proxy.lua https://proxy_addr:8080`

via_proxy.lua:

    wrk.path = "https://google.com/"
    wrk.headers["Host"] = "google.com:443"
    wrk.headers["Proxy-Authorization"] = "Basic dXNlcjE6cGFzc3dvcmQx"
    wrk.headers["Proxy-Connection"] = "Keep-Alive"

`tcpdump` shows that using `wrk` like this still sends `GET` not `CONNECT` request. Whereas `curl` sends `CONNECT`.

**Comment by wg** [comment]
@povilasb try implementing the `request()` function which can return an arbitrary HTTP request

**Comment by povilasb** [comment]
@wg I've made a PR for a basic proxy support https://github.com/wg/wrk/pull/164. Could you take a look?

**Comment by wg** [comment]
Thanks for the pull request @povilasb! I don't believe all of that code is necessary though. For a regular HTTP proxy request you can do something this:

```lua
local connected = false
local host = "www.bing.com"
local path = "/"
local url  = "http://" .. host .. path

wrk.headers["Host"] = host

request = function()
   if not connected then
      connected = true
      return wrk.format("CONNECT", host)
   end

   return wrk.format("GET", url)
end
```
`./wrk -t1 -c1 -d30s -s proxy.lua http://localhost:8080/`

That won't work for proxying HTTPS requests, but that's such an edge case that I don't consider it worth adding such complexity to wrk.
