### ISSUE TITLE
Contribute: Read content from a file and post

### ISSUE THREAD

**Issue by 208rishabh** [wg/wrk#165]
Hi,

I have used WRK for benchmarking purposes. For my particular use case, I created a lua script which reads data from a csv file and posts to the application. I would like to contribute that here for others to use. Do you think its worth? Please give your feedback.

**Comment by wg** [comment]
Hi @208rishabh, glad to hear you're finding wrk useful! I'd encourage you to publish your example script in a github repository of your own. I don't intend to include too many scripts with wrk itself because each one adds maintenance overhead.
