### ISSUE TITLE
will proxy option be provided as part of command line parameter in this tool

### ISSUE THREAD

**Issue by techwizardg** [wg/wrk#166]
We want to use your tool to test http proxy . How do we do that as there is no option to set proxy

**Comment by wg** [comment]
See https://github.com/wg/wrk/issues/162#issuecomment-143963862 and @povilasb's fork: https://github.com/povilasb/wrk/commits/feature/proxy-support

**Comment by povilasb** [comment]
@wg, I guess it would be worth to implement CLI options for proxy information. As it would be a lot easier for users.
