### ISSUE TITLE
Clarification on a stat you report

### ISSUE THREAD

**Issue by GuardRex** [wg/wrk#169]
We were just discussing wrk benchmarks in the [ASP.NET 5 benchmarks repo](https://github.com/aspnet/benchmarks/issues/20#issuecomment-147042893). Could you clarify one of your stats for me:
```
Running 30s test @ http://127.0.0.1:8080/index.html
    12 threads and 400 connections
    Thread Stats   Avg      Stdev     Max   +/- Stdev
      Latency   635.91us    0.89ms  12.92ms   93.69%
      Req/Sec    56.20k     8.07k   62.00k    86.54%
    22464657 requests in 30.00s, 17.76GB read
  Requests/sec: 748868.53
  Transfer/sec:    606.33MB
```
You have a "+/- Stdev" column with percentage (%) units on the values. The RPS row shows 56.20K RPS, 8.07K SD, a 62.00K maximum RPS, and an 86.54% +/- Stdev. It's the 86.54% value ... how is that interpreted? ... how is that calculated?

**Comment by wg** [comment]
Hi @GuardRex, +/- Stdev is the percentage of requests that fall within 1 standard deviation of the average.
