### ISSUE TITLE
How to specify environment variables to scripts?

### ISSUE THREAD

**Issue by Dynom** [wg/wrk#176]
I'd like to be able to do the following:

```sh
TOKEN="foo"; wrk -s someScript.lua https://somedomain.com
```

where someScript.lua contains a minimal:

```lua 
wrk.method = "POST"
wrk.body   = '...'
wrk.headers["Content-Type"] = "application/json"
wrk.headers["X-Authentication-Token"] = os.getenv("TOKEN")
```

If this isn't currently possible I'd like to propose a feature request, else I'd like an example script on how to accomplish this. I've searched trough the issues, but I couldn't find a similar question.

**Comment by pborzenkov** [comment]
@Dynom It is possible. Just remove the semicolon, otherwise the variable is not being exported to child processes:

TOKEN="foo" wrk -s someScript.lua https://somedomain.com

Or export it before running wrk:
export TOKEN="foo"
wrk -s someScript.lua https://somedomain.com

**Comment by Dynom** [comment]
That seems to work, thanks!
