### ISSUE TITLE
Question about TCP performances

### ISSUE THREAD

**Issue by acastaner** [wg/wrk#185]
This is more of a question than an issue. I was wondering how your tool deals with the Linux TCP stack - which is great, but sometimes can have issues in scaling to extreme high performance. The kernel will do a lot of interrupts for instance, capping performances. This is why many companies, especially those doing pure networking on a Linux kernel, develop their own stack, buy one, and/or use DPDK.

Any details you could share on this would be great. I'm not a good enough dev to understand that from the source code, I admit!

**Comment by wg** [comment]
Hi @acastaner, wrk just uses the regular async socket APIs, nothing fancy. The highest performance I've seen reported is > 6M requests/sec via the Framework Benchmarks project: https://www.techempower.com/benchmarks/

They're using a very old build of wrk, and 4.0.0+ should be noticeably faster but I don't know where you'd start running into kernel stack performance issues.
