### ISSUE TITLE
Unable to install wrk2 in osx-elcapitan

### ISSUE THREAD

**Issue by kalyanjennu** [wg/wrk#186]
Hi,
 I tried installing wrk2 in OS X elcapitan. I am getting below error.

CC src/wrk.c
In file included from src/wrk.c:3:
src/wrk.h:11:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make: *** [obj/wrk.o] Error 1

**Comment by yxy** [comment]
obvisouly you should install openssl-dev library

but it will be a simple way to solve your problem. 

install wrk using brew, see blew command

   brew install wrk

It will automatic resolve all wrk's all dependces

**Comment by paranoidjk** [comment]
may be ` brew link openssl --force`

**Comment by PiotrGoralczyk** [comment]
In my case modifying the Makefile and adding `-I/usr/local/opt/openssl/include` to `CFLAGS` and `-L/usr/local/opt/openssl/lib` to `LIBS` did the trick. Don't forget to `make clean` before rebuilding. ;)

When you `brew install openssl`, you get a message that explains it.

**Comment by PiotrGoralczyk** [comment]
@kalyanjennu: By the way, wrk2 is a separate project: https://github.com/giltene/wrk2

**Comment by wg** [comment]
Thanks for the replies everyone!
