### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by yatskovsky** [wg/wrk#187]
Hi, how to compile this under Windows (x64) platform?

**Comment by infeng** [comment]
i have same problem

**Comment by fatso83** [comment]
I haven't tried, but the easiest approach is usually to install the Mingw64 tools package, which allows you to compile on the Windows platform using a unix tool set. That will build a standard win32 executable. Failing that, you could try doing the same on Cygwin.

**Comment by zs-zs** [comment]
Hi, I was able to compile it under Windows using Cygwin, however the end result is not usable, see #195

**Comment by wg** [comment]
Unfortunately running wrk on Windows is completely unsupported and unlikely to work.

**Comment by obastemur** [comment]
Was looking for the same question; 

Just wanted to note an alternative solution that is using new Ubuntu `bash` on `Windows 10` . Wrk works as is and so far happy with the performance.

**Comment by wg** [comment]
Thank you for the follow up @obastemur! It's great to hear that the new Linux subsystem for Windows is robust enough to run wrk.

**Comment by xbuddhi** [comment]
use Apache JMeter for Windows

**Comment by hgc81538** [comment]
Use https://github.com/rakyll/hey
Performance is quite good.
