### ISSUE TITLE
Simple scenario using Lua script

### ISSUE THREAD

**Issue by Nawa** [wg/wrk#189]
Is it possible to measure latency of two requests together?
1. GET request that returns json response
2. GET request based on parsed result of first

**Comment by fatso83** [comment]
Set up the `response` hook as seen in [this example script](https://github.com/wg/wrk/blob/master/scripts/auth.lua). You will receive the body as a parameter to your function. 

Either manually parse the response, or use [one of the JSON libs for Lua](http://lua-users.org/wiki/JsonModules) to do it for you.

This [fine script](https://gist.github.com/anonymous/91dc4d8a752d7916d48c) shows how to work with multiple URLs and is from a nice [Digital Ocean tutorial](https://www.digitalocean.com/community/tutorials/how-to-benchmark-http-latency-with-wrk-on-ubuntu-14-04) that does a lot better job of explaining the innards of `wrk` than the official docs do. 

- [Wrk API reference](https://github.com/wg/wrk/blob/master/SCRIPTING)
- [LUA reference](http://www.lua.org/manual/5.1/manual.html#pdf-table.concat)

All in all this should be enough to accomplish what you seek.

**Comment by fatso83** [comment]
For your simple scenario, you might also be interested in manually coupling this together using http://github.com/sidorares/node-wrk.
