### ISSUE TITLE
[discussion] [help needed] Log each request time

### ISSUE THREAD

**Issue by hellboy81** [wg/wrk#190]
Is there possible to log time of each request during benchmarking?

Is there possible with lua scripting?
Is there ready-to-use solutions?

**Comment by fatso83** [comment]
Yes.

This [fine script](https://gist.github.com/anonymous/91dc4d8a752d7916d48c) shows how to work with multiple URLs and is from a nice [Digital Ocean tutorial](https://www.digitalocean.com/community/tutorials/how-to-benchmark-http-latency-with-wrk-on-ubuntu-14-04) that does a lot better job of explaining the innards of `wrk` than the official docs do. 

- [Wrk API reference](https://github.com/wg/wrk/blob/master/SCRIPTING)
- [LUA reference](http://www.lua.org/manual/5.1/manual.html#pdf-table.concat)

All in all this should be enough to accomplish what you seek.
