### ISSUE TITLE
CentOS 6 - make Command not found

### ISSUE THREAD

**Issue by capsocrates** [wg/wrk#191]
When following the instructions [here](https://github.com/wg/wrk/wiki/Installing-Wrk-on-Linux), I get this error
```
make: /usrl/local/bin/gcc: Command not found
make: *** [obj/wrk.o] Error 127
```
right after this line 
```
CC src/wrk.c
```
when running the `make` command.

It looks to me like some kind of typo. I don't recognize `/usrl` as a valid directory--it certainly doesn't exist on my box.

I do have gcc installed.

**Comment by capsocrates** [comment]
My workaround was to specify `CC` as a valid compiler. In my case, `make CC=clang` worked fine. I imagine `make CC=gcc` would also work.

**Comment by fatso83** [comment]
@capsocrates you could fix the typo and submit a pull request. then others would have a good time as well.

**Comment by capsocrates** [comment]
I couldn't find the line to fix it when I searched the repo.
