### ISSUE TITLE
Ask for co-maintainers

### ISSUE THREAD

**Issue by fatso83** [wg/wrk#193]
It seems that this project is at a bit of standstill. If the amount of PRs and issues are overwhelming, why not ask for co-maintainers to step up and help maintain the project and keep it alive? Create an issue where you are asking for help and see what comes up.

There is currently missing documentation on inner workings, pull requests waiting months to be merged, and lots of unanswered questions (that might or might not deserve an answer).

**Comment by wg** [comment]
Hi @fatso83, thank you for your enthusiasm in replying to open issues. This project is not at a standstill, rather it is mature and stable. AFAIK there are no critical outstanding bugs. PRs are reviewed and incorporated appropriately as time permits. Everyone is welcome to contribute constructive comments on open issues.

**Comment by fatso83** [comment]
Thanks for a swift reply! I have no reservations to the stability of `wrk` at all. Just saying :)

I raised the issue based on a swift browse of the issues and the PRs, so my perspective is that of someone trying to check out the health of a project before incorporating it into a workflow. We just scrapped [locust](https://github.com/locustio/locust) in favor of `wrk` (for creating performance reports in json so that we can automatically track performance over time) just out of this reason: 

- issues were not being closed after months
- pull requests implementing new features were not being integrated

It turned out the maintainers no longer had any time or interest for the project and so there is an ongoing task of getting new ones. I checked the issues and saw you interacted in some of them, so I knew the project wasn't dead, but since all these minor non-invasive PRs (typo fixes, additions to README, etc) weren't being touched it seemed as if you might lack time.

As a co-maintainer of [Sinon](https://github.com/sinonjs/sinon) I know very well that all the noise arising from a popular project can be very time consuming, and seeing PRs lying around for a year, I was thinking this might be an indication of the project perhaps needing some help in answering and closing issues. I see a lot of the issues could have been closed (answered by others + inactivity), and seeing activity on the issue tracker helps in keeping an image of a living project. Of course you might be lucky to have stray passersby answering a ticket or two, but they will not be able to close them, or help integrating smaller changes. Some "official" helpers often invest a bit more time and effort into doing this.

Just a suggestion of course.

P.S. I wasn't suggesting myself :-)
