### ISSUE TITLE
Lua panic under Windows

### ISSUE THREAD

**Issue by zs-zs** [wg/wrk#195]
Hi,

I successfully compiled wrk under Windows 8.1 using Cygwin, however I get errors when trying to actually start benchmarking:

    $ ./wrk.exe http://localhost:8888/
    PANIC: unprotected error in call to Lua API (attempt to index a nil value)

The error comes from lib_aux.c from LuaJIT (I don't know if it helps or not).

**Comment by fatso83** [comment]
Might sound like an idiot's suggestion, but maybe try compiling it using Mingw instead of Cygwin? There are some small differences that hopefully could be in your favor. Worth a try.

**Comment by wg** [comment]
Unfortunately running wrk on Windows is completely unsupported and unlikely to work.
