### ISSUE TITLE
Is it possible to access global data from request() function

### ISSUE THREAD

**Issue by Vistian** [wg/wrk#218]
In the setup.lua example script, is it possible for all threads to be able to access the threads table from the init(), request(), and response() functions? When I try to do so currently, the table is empty and has a different address for each thread. It seems only the setup() and done() functions can access this memory.

**Comment by wg** [comment]
No, wrk is designed for completely independent threads of execution which eliminates the overhead of synchronization, but does preclude communication between threads. It should be possible to call one of your platform's shared memory APIs via LuaJIT's FFI though.
