### ISSUE TITLE
Linux arm64 support

### ISSUE THREAD

**Issue by stevewin64** [wg/wrk#225]
I am using Ubuntu 16.04 arm64 version, and encountering build errors due to LuaJIT not supporting Linux arm64.

Is it possible to build wrk without LuaJT (can base functionality be available without it).

Are there plans for LuaJIT to support Linux arm64?

**Comment by stevewin64** [comment]
Found information on status of LuaJIT arm64 port at LuaJIT project https://github.com/LuaJIT/LuaJIT/issues/26

**Comment by petar-jovanovic** [comment]
You should be able to use ARM64 interpreter of LuaJIT for the time being.

**Comment by stevewin64** [comment]
Looked at this a bit more - an issue is that LuaJIT is used to generate an object module for the package (bytecode.o from wrk.lua) - so just having the interpreter won't work.

Question becomes - is there a way to build/run wrk without LuaJIT support on an architecture

**Comment by wg** [comment]
Unfortunately not, LuaJIT is deeply integrated and wrk cannot function without it. It's my understanding that the upcoming LuaJIT 2.1 release will support arm64, so I'd suggest giving the beta a try. Should be easy enough to put the tar.gz in deps/ and update the Makefile, though I don't know if there have been breaking changes.
