### ISSUE TITLE
do not work on raspberry pi 3

### ISSUE THREAD

**Issue by sincoder** [wg/wrk#226]
get bus error

pi@pi3:~/wrk $ ./wrk http://192.168.0.109
Running 10s test @ http://192.168.0.109
  2 threads and 10 connections
Bus error

**Comment by stamster** [comment]
My guess is that you'd need to fine-tune Kernel params (network, sockets, etc.).

**Comment by scottlamb** [comment]
I hit the same problem. I added `-g -fno-omit-frame-pointer` to `CFLAGS` and `-g` to `LDFLAGS` then ran under gdb:

```
$ gdb ./wrk
...
(gdb) run http://localhost:1337/
Starting program: /home/slamb/git/wrk/wrk http://localhost:1337/
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x7119b460 (LWP 8898)]
[New Thread 0x7077b460 (LWP 8899)]
Running 10s test @ http://localhost:1337/
  2 threads and 10 connections

Program received signal SIGBUS, Bus error.
[Switching to Thread 0x7119b460 (LWP 8898)]
0x0004c01c in stats_record (stats=<optimized out>, n=539) at src/stats.c:25
25          __sync_fetch_and_add(&stats->data[n], 1);
```

It looks like the [Legacy __sync Built-in Functions for Atomic Memory Access](https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/_005f_005fsync-Builtins.html#_005f_005fsync-Builtins) aren't supported on ARM.

I was able to get it to run (and apparently work) with this patch:

```
diff --git a/src/stats.c b/src/stats.c
index 92409ec..f802ff8 100644
--- a/src/stats.c
+++ b/src/stats.c
@@ -21,12 +21,19 @@ void stats_free(stats *stats) {

 int stats_record(stats *stats, uint64_t n) {
     if (n >= stats->limit) return 0;
+#if 0
     __sync_fetch_and_add(&stats->data[n], 1);
     __sync_fetch_and_add(&stats->count, 1);
     uint64_t min = stats->min;
     uint64_t max = stats->max;
     while (n < min) min = __sync_val_compare_and_swap(&stats->min, min, n);
     while (n > max) max = __sync_val_compare_and_swap(&stats->max, max, n);
+#else
+    stats->data[n]++;
+    stats->count++;
+    if (n < stats->min) stats->min = n;
+    if (n > stats->max) stats->max = n;
+#endif
     return 1;
 }
```

but it looks like this function was intended to be thread-safe? My patch isn't thread-safe.

One obvious solution would be to use a `pthread_mutex_t`, but were atomics used because of performance problems with the simpler mutex approach? If so, another option would be to maintain stats in a thread-local structure, then combine them after all threads have finished.

**Comment by wg** [comment]
Thanks for the detailed response @scottlamb! The stats buffer takes a lot of memory, so having one instance per thread wouldn't be great. Stats collection really is performance-critical when benchmarking servers capable of doing millions of requests/sec, so having everything block on a mutex wouldn't be great either.

**Comment by ycycn** [comment]
So, that means i can't play wrk on Pi :(

**Comment by wg** [comment]
Actually I suspect this may be due to an alignment issue rather than ARM not supporting those atomic intrinsics. Unfortunately I don't have suitable hardware to test on. However you may want to try this patch: https://github.com/jmencak/wrk/commit/40d56639e916b7afc92febfabc86f5d6bb8bc6b7

**Comment by ycycn** [comment]
Yes! U R Right !
successed in raspbian on Raspberry Pi 3 B !
Thank you !

```
root@raspberrypi:/# wrk -t12 -c512 -d16s http://192.168.1.111:8000
Running 16s test @ http://192.168.1.111:8000
  12 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    18.95ms    3.89ms 253.01ms   89.93%
    Req/Sec     2.24k   146.57     4.20k    91.71%
  429281 requests in 16.09s, 46.67MB read
Requests/sec:  26676.42
Transfer/sec:      2.90MB
root@raspberrypi:/# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@raspberrypi:/#
```

**Comment by jmrnilsson** [comment]
Can confirm i get these on raspberry pi 4 as well. Will try with patch..

**Comment by WGH-** [comment]
I'm having the same issue on Orange Pi Zero (I guess the problem is the same for all ARMs)

`dmesg`:
```
[1141145.918455] 8<--- cut here ---
[1141145.918466] Unhandled fault: alignment exception (0x001) at 0xb5d7f0a4
[1141145.918479] pgd = da1a2e09
[1141145.918486] [b5d7f0a4] *pgd=46c78835, *pte=00000000, *ppte=00000000
```

`gdb`:
```
Thread 3 "wrk" received signal SIGBUS, Bus error.
[Switching to Thread 0xb0549460 (LWP 25795)]
0x00404728 in stats_record ()
(gdb) bt
#0  0x00404728 in stats_record ()
#1  0x0040420a in _start ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) x/i $pc
=> 0x404728 <stats_record+44>:  adds    r6, r6, r4
```
