### ISSUE TITLE
Document how to use the -H command line option

### ISSUE THREAD

**Issue by italomaia** [wg/wrk#227]
Just an example within the readme would be really nice.

**Comment by stefanos82** [comment]
@wg: I agree with @italomaia, the documentation need to be extended just a bit.

For example, I wanted to check Lua script example and did not know how to do it, in spite of the existence of `SCRIPTING` file.

Real life examples are always more than welcomed.

Also, are there any performance penalties if we surpass a specific number of threads and / or connections?

**Comment by wg** [comment]
Thanks for the suggestion.

@stefanos82 correct use of threads & connections really depends on what you're trying to test. For general benchmarking purposes threads should be <= the number of virtual CPUs in the load generator. If the server is running on the same CPUs then it needs to be even lower. Then you can tune connections until you find the max throughput rate or minimum latency.

On the other hand if you're looking at how a server will perform under load you may want to test a whole range of connection numbers and record the latencies at each point.
