### ISSUE TITLE
Bug inside Makefile

### ISSUE THREAD

**Issue by stefanos82** [wg/wrk#230]
@wg I downloaded version 4.0.2 and line 23 in Makefile causes a fatal error message upon compilation completion.

```
LUAJIT src/wrk.lua
fatal: Not a git repository (or any of the parent directories): .git
LINK wrk
```

You can detect the problem at this line: I have no .git inside the extracted source.

Is it something a user should care about, is it of mandatory use ? Also, `.gitignore` is located in root directory.

 `VER  ?= $(shell git describe --tags --always --dirty)`

**Comment by wg** [comment]
The canonical version comes from git but you can build without it: `make VER=xyz`
