### ISSUE TITLE
How to use wrk do the multiple domain testing?

### ISSUE THREAD

**Issue by shiyun10** [wg/wrk#232]
here is my script, but it's not work! 
./wrk -t1 -c2 -d10 -s script/multiple.lua http://google.com

multiple.lua
function request()
  local url ={"http://google.com","http://yahoo.com","http://github.com"}
  urlIndex= math.random(3)
  currentUrl = url[urlIndex]
  return wrk.format(nil,currentUrl)
end

**Comment by wg** [comment]
See https://github.com/wg/wrk/blob/master/scripts/addr.lua but be aware that keep-alive connections won't reconnect until they are forced to.
