### ISSUE TITLE
Use lua script to simulate real user traffic

### ISSUE THREAD

**Issue by kkumar-fk** [wg/wrk#235]
Hi all,

I am just trying out lua today for the first time, so apologize if this is
answered already, but I could not find the answer yet. Is there a way
to do something like:

for iteration in 1 to 100
           connect
           make 'n' requests
           close

directly via lua instead of writing a bash script to do the same and add
numbers, etc? Preferably the loop should be infinite and the test should
run for the time specified in '-d' option.

Thanks in advance.

**Comment by steers** [comment]
Sounds like you should try combining the `stop.lua` and `pipeline.lua` example scripts. Seems pretty close to your use-case from what I can tell.

**Comment by kkumar-fk** [comment]
Thanks for the feedback, I will try that..

**Comment by djuarezg** [comment]
@kkumar-fk How did you do this in the end? Did you manage?
