### ISSUE TITLE
Unable to compile wrk under osx

### ISSUE THREAD

**Issue by gnumer** [wg/wrk#237]
After following https://github.com/wg/wrk/wiki/Installing-wrk-on-OSX, this build error occurs. 

```
CC src/wrk.c
CC src/net.c
CC src/ssl.c
CC src/aprintf.c
CC src/stats.c
CC src/script.c
CC src/units.c
CC src/ae.c
CC src/zmalloc.c
CC src/http_parser.c
LUAJIT src/wrk.lua
/bin/sh: Pro: command not found
make: *** [obj/bytecode.o] Error 127
```

**Comment by cocojas** [comment]
You have something in your `PATH` with a space in it. Remove it from your `PATH` and use the one suggested when you build. For example: `PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin make`

**Comment by wg** [comment]
Thanks @cocojas!
