### ISSUE TITLE
make: *** [obj/lib/libssl.a] Error 2

### ISSUE THREAD

**Issue by lithdam** [wg/wrk#239]
# i got an error when i install the wrk

my os is centos 6.4
make[1]: Leaving directory `/root/wrk/obj/openssl-1.0.2g'
make: **\* [obj/lib/libssl.a] Error 2
# i use follow coman to install it

sudo  yum groupinstall 'Development Tools'
sudo yum install  openssl-devel
sudo yum install  git
git clone https://github.com/wg/wrk.git
cd wrk
make

**Comment by channelcat** [comment]
This fixed it for me - https://github.com/wg/wrk/pull/211

**Comment by akzi** [comment]
installing man3/SSL_write.3
installing man3/d2i_SSL_SESSION.3
i2d_SSL_SESSION.3 => d2i_SSL_SESSION.3
installing man3/ssl.3
SSL.3 => ssl.3
make[1]: Leaving directory `/home/skyinno/akzi/wrk/obj/openssl-1.0.2g'
make: *** [obj/lib/libssl.a] Error 2
----------------------------------------------------------------------
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
----------------------------------------------------------------------
skyinno@skyinno1:~/akzi/wrk$ sudo apt-get install libssl-dev && sudo apt-get install openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 153 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 153 not upgraded.
------------------------------------------------------------------------------

**Comment by wangwanchao** [comment]
when i make install wrk on cygwin，i have the error
`
Building OpenSSL...
Operating system: x86_64-pc-cygwin
You need Perl 5.
make: *** [Makefile:94：obj/lib/libssl.a] error 1
`
then, I execute the :
`apt-cyg install perl`
the cmd 'make' works;
