### ISSUE TITLE
How to pass client certificate with the request

### ISSUE THREAD

**Issue by suni1mp** [wg/wrk#240]
How can i pass cert file as part of wrk request
its a https request and i need pass client cert file as show in curl statement:
curl --cert certificate_file.pem:password https://URL

**Comment by suni1mp** [comment]
hi @wg  , Request to help me finding the answer for the above query, lot of people are dependent on this feature

**Comment by wg** [comment]
Hi @suni1mp, wrk doesn't support client certificates at this time.
