### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by sje397** [wg/wrk#243]
I followed the build instructions for Centos7, but when I run wrk I get:

zmalloc: Out of memory trying to allocate 960000000040 bytes

**Comment by wg** [comment]
What is the command line you're using? My first guess is that you're using a very long timeout?

**Comment by sje397** [comment]
Yes, it was a long timeout (I incorrectly put ms instead of s). But, the
same command worked find on my own machine (macbook) whereas the failure
happened on one with more resources (aws largish instance).

**Comment by wg** [comment]
Did you attempt it in a Linux VM on the Macbook or in macOS? Linux has a kernel parameter `vm.overcommit_memory` that allows allocating more memory than available, perhaps macOS does too. wrk won't actually touch the allocated memory unless a requests takes an abnormally long time to complete.
