### ISSUE TITLE
Unable to understand the Thread Stats results

### ISSUE THREAD

**Issue by debbiswal** [wg/wrk#247]
Hi ,

I ran the below command against my node.js api and got the results

Command :
wrk -t12 -c400 -d30s http://127.0.0.1:8080/getdata?key=cst1

Output:
Running 30s test @ http://127.0.0.1:8080/getdata?key=cst1
    12 threads and 400 connections
    Thread Stats   Avg      Stdev     Max   +/- Stdev
      Latency   635.91us    0.89ms  12.92ms   93.69%
      Req/Sec    56.20k     8.07k   62.00k    86.54%
    22464657 requests in 30.00s, 17.76GB read
  Requests/sec: 748868.53
  Transfer/sec:    606.33MB

But I am unable to understand the output properly.
What are these Avg,Stdev,Max,+/- Stdev values.
Are these values are my API response time.
What these Latency,Req/Sec represents.

I know , this forum is only for issues , but I did not find any correct answer for this , so posted it here.
It would be really helpful , if some one guides me.

Thanks in Advance....

**Comment by arivero** [comment]
req/seq is intriguing. Consider

```
Running 30s test @  /luaRedis
  2500 threads and 20000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    79.41ms   99.43ms   2.00s    98.86%
    Req/Sec    31.26     26.15   242.00     82.83%
  1080925 requests in 30.27s, 191.69MB read
  Socket errors: connect 694, read 728, write 1425, timeout 4898
Requests/sec:  35710.03
Transfer/sec:      6.33MB
```

```
Running 30s test @ ping.txt
  2500 threads and 20000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    79.07ms  127.66ms   2.00s    95.49%
    Req/Sec    31.14     18.69   232.00     67.17%
  1954725 requests in 30.27s, 426.81MB read
  Socket errors: connect 4873, read 559, write 1884, timeout 12096
Requests/sec:  64567.08
Transfer/sec:     14.10MB
```

Same threads and conections, same Req/Sec thread stat, but two times the total requests/sec
