### ISSUE TITLE
Adding luasec to LuaJIT installed with wrk

### ISSUE THREAD

**Issue by marcandrews** [wg/wrk#249]
How do I add luasec to the version of to LuaJIT installed with wrk?

(I'd like to make HTTPS requests from within my lua scirpt.)

**Comment by wg** [comment]
Hey @marcandrews, you might be able to set `package.path` but I've never tried anything like this. wrk is inherently asynchronous, so doing long-running, synchronous tasks from within a lua script isn't a good idea.

**Comment by marcandrews** [comment]
This was a while back, but what I did was install LuaJIT, libssl, and then build wrk with `$ make WITH_LUAJIT=/path/to/lua_jit WITH_OPENSSL=/path/to/open_ssl`.
