### ISSUE TITLE
wrk doesn't close fds correctly?

### ISSUE THREAD

**Issue by recoilme** [wg/wrk#251]
I have massive read errors on multithreaded test of simple server on libevent
```
wrk -t 5 -c 1000 http://127.0.0.1:9876/
Running 10s test @ http://127.0.0.1:9876/
  5 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    23.06ms   12.43ms 103.07ms   70.00%
    Req/Sec     4.93k     1.63k   10.69k    75.20%
  246287 requests in 10.07s, 37.11MB read
  Socket errors: connect 0, read 979, write 0, timeout 0
Requests/sec:  24460.38
Transfer/sec:      3.69MB
```
Related issue with code examples to reproduce:
https://github.com/libevent/libevent/issues/453

**Comment by wg** [comment]
If you're referring to wrk not closing all the active client sockets when stopping then yes, it doesn't need to because the OS will clean up those resources when the process exits.
