### ISSUE TITLE
SCRIPTING doc questions

### ISSUE THREAD

**Issue by qrilka** [wg/wrk#252]
From `SCRIPTING` (section `Setup`):
```
  Only boolean, nil, number, and string values or tables of the same may be
  transfered via get()/set() and thread:stop() can only be called while the
  thread is running.
```
* What does `tables of the same` mean? Maybe some word is missing?
* How `thread:stop()` could be called in `setup` "while the thread is running" when before that it's said that "threads have been initialized but not yet started"?

**Comment by wg** [comment]
Hi @qrilka, "tables of the same" means the tables can contain any of the values listed. `thread:stop()` cannot be called during setup, it can be called later.
