### ISSUE TITLE
Ressource fetching

### ISSUE THREAD

**Issue by Yamakaky** [wg/wrk#255]
Is there a way for wrk to parse the HTML response and also download the css, js, images? It would be more accurate, as tls sessions would be kept and HTTP/2 could do it's job.

**Comment by wg** [comment]
You could use a Lua script to parse downloaded resources and generate new lists of request paths based on the contents, but wrk is designed for benchmarking not simulating realistic user load. You'd probably get better results from a tool designed for that.

**Comment by Yamakaky** [comment]
I mean, benchmarking something a user would never do is not very useful, you want to test something a user would do.
