### ISSUE TITLE
Did you do some work about the dpdk?

### ISSUE THREAD

**Issue by likezjuisee** [wg/wrk#264]
Did you try to build the wrk with the dpdk? It may make the wrk more faster.

**Comment by wg** [comment]
I haven't, it's my understanding that the DPDK is specific to Linux and certain NIC drivers. It'd be really cool to see how a HTTP benchmarking tool could benefit from the DPDK but that's not something I'd implement for wrk since it isn't portable and wrk is pretty darn fast already.

**Comment by likezjuisee** [comment]
OK, I see. Thanks.
