### ISSUE TITLE
JSON Post

### ISSUE THREAD

**Issue by u2** [wg/wrk#267]
```
wrk.method = "POST"
wrk.body   = '{"jsonrpc":"2.0","method":"cita_sendTransaction","params":["abcd"],"id":2}'
wrk.headers["Content-Type"] = "application/json"
```

Not support "application/json" post, it taken it as get method.

While I changed it to "application/x-www-form-urlencoded", the method is right.

**Comment by daodennis** [comment]
Have you tried urlencoding the payload and seeing if that works?

**Comment by exAspArk** [comment]
Any updates on the issue?

**Comment by turtleDev** [comment]
works fine on v4.0.2.2

**Comment by wg** [comment]
Thanks @turtleDev!

**Comment by jdhao** [comment]
Here is an example on how to post request as `application/json`, it works fine for me on wrk 4.2.0: https://stackoverflow.com/a/54457442/6064933.
