### ISSUE TITLE
stats meaning

### ISSUE THREAD

**Issue by knasim** [wg/wrk#268]
can you explain `Max` is for in the Latency and Req/Sec stats.  
actually even better would there be any docs that explain all of the columns in the result ?  Not the parameters passed in.

**Comment by knasim** [comment]
Max   +/- Stdev

**Comment by wg** [comment]
Max is the maximum value seen, +/- Stdev is the percentage of requests within one standard deviation of the mean. Could definitely be documented better, will keep that in mind.

**Comment by ravink83** [comment]
I have got these results, but am struggling to understand the standard devition % value of the results.  what does the percventage of the standard deviations exactly indicate ? 
Your help is highly appreciated.
Avg response time :  57.03
+/- Std. Dev.(%) : 98.72
std. dev	: 414.21ms
max		: 15.39s
lat.Dist.50%	: 24.84ms
lat.Dist.75%	: 26.92ms
 	90%)	: 29.84ms
lat.Dist.99%	: 892.42ms
