### ISSUE TITLE
Disabled SSL certificate verify

### ISSUE THREAD

**Issue by ruanlinqi** [wg/wrk#269]
Hi developers:
    Nowadays we made a large scale security static analysis on several open source projects, and found some mistakes in wrk-4.0.1. In the @src/ssl.c:42:
    SSL_CTX *ssl_init() {
        [...]
        if ((ctx = SSL_CTX_new(SSLv23_client_method()))) {
            SSL_CTX_set_verify(ctx, SSL_VERIFY_NONE, NULL);
            SSL_CTX_set_verify_depth(ctx, 0);
            SSL_CTX_set_mode(ctx, SSL_MODE_AUTO_RETRY);
            SSL_CTX_set_session_cache_mode(ctx, SSL_SESS_CACHE_CLIENT);
        }
    }
    return ctx;
}

  The parameter SSL_VERIFY_NONE here can not configure this built-in certificate validation,so the handshake can continue even the cert is invalid.We recommand you use SSL_VERIFY_PEER to guarantee the security.We have send the bug report to Ubuntu launchpad,and also inform you of such news.Here are the link:
https://bugs.launchpad.net/ubuntu/+source/wrk/+bug/1677518

**Comment by knasim** [comment]
@ruanlinqi  "so the handshake can continue even the cert is invalid" - even if no cert is sent with the request ?

**Comment by wg** [comment]
Thanks, wrk is a benchmarking tool and as such should be able to test HTTPS servers with self-signed certificates without needing to configure a CA store. I don't think cert verification is necessary for such a tool.

**Comment by kodmanyagha** [comment]
We don't want ssl check feature. This is just a testing tool, not sending real user requests. Is it really hard to make it?
