### ISSUE TITLE
How to test upload 3MB file?

### ISSUE THREAD

**Issue by timezstyle** [wg/wrk#274]
I don't know how to setup lua file (for upload 3MB file). Can someone help me ?

**Comment by marcospereira** [comment]
See this script from PlayFramework:

https://github.com/playframework/prune/blob/master/src/main/resources/com/typesafe/play/prune/assets/wrk_upload.lua#L1-L36

Not sure if wrk has some more specific or better way to do that, but this is working for us.

**Comment by stereobooster** [comment]
It would be nice to collect examples of different lua scripts from real open source projects in a wiki

**Comment by wg** [comment]
Thanks @marcospereira!
