### ISSUE TITLE
Feature in need: WRK did not support https/ssl OCSP extension

### ISSUE THREAD

**Issue by arthurkiller** [wg/wrk#278]
need the ability for https test

**Comment by wg** [comment]
Hey @arthurkiller, this is probably outside the scope of what wrk is designed for. wrk is primarily a HTTP benchmarking tool and does not even verify server certificates. Making OSCP requests would just slow things down when benchmarking.

**Comment by arthurkiller** [comment]
Thx for reply , and I have done wrk-go especially for https bench marking

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️

Arthur lee
