### ISSUE TITLE
Wrong request count

### ISSUE THREAD

**Issue by lilydjwg** [wg/wrk#280]
I find that, for n connections, wrk counts m less requests than the web server actually sees / logs, where m <= n.

This seems to be caused by wrk may stop without running the `response_complete` callback. Maybe wrk can run the last requests till complete, or indicate there are more requests hit the web server than which wrk knows have completed

**Comment by ms2008** [comment]
referrer #119

**Comment by wg** [comment]
Thanks @ms2008! wrk no longer has a calibration phase, but requests could be in flight when the testing interval ends and wrk isn't going to wait for them to complete.
