### ISSUE TITLE
wrk.thread:stop() doesn't stop load test

### ISSUE THREAD

**Issue by retrohacker** [wg/wrk#281]
It is possible I may be misunderstanding the purpose of `wrk.thread:stop()`. When all of the threads have called `stop()`, the load test continues running.

Repro:

```lua
local counter = 0
function setup(thread)
  thread:set("id", counter)
  print("Setup", counter)
  counter = counter + 1
end

function response()
  counter = counter + 1
  if counter == 100 then
    print(id,"done")
    wrk.thread:stop()
  end
  return wrk.format()
end
```

Run with `wrk -t 4 -c 20 -d 60s -s ./wrk.lua [URL]`

Output:
```
Setup	0
Setup	1
Setup	2
Setup	3
Running 1m test @ http://127.0.0.1:7001
  4 threads and 20 connections
0	done
1	done
2	done
3	done <-- this is reached almost instantly (server is just a ping endpoint)
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    27.12ms    8.56ms  89.12ms   91.75%
    Req/Sec   179.75     37.38   222.00     90.00%
  400 requests in 1.00m, 83.59KB read <-- load test continued for whole duration
  Non-2xx or 3xx responses: 400
Requests/sec:      6.67
Transfer/sec:      1.39KB
```
(arrows added for comment)

Even though all threads have called `wrk.thread:stop()` the load test continues for the whole duration.

**Comment by Subtalime** [comment]
Did you get anywhere with this issue? Just encountered the same.

**Comment by retrohacker** [comment]
Sorry @Subtalime,

I was able to hack through this at the time. It was long enough ago that I don't remember how. IIRC I restructured my project so I didn't have to rely on `stop()`

**Comment by djuarezg** [comment]
Does anyone have any way of overcoming this?

**Comment by retrohacker** [comment]
@djuarezg I eventually migrated to https://github.com/mcollina/autocannon
