### ISSUE TITLE
Incorrect Host Header in 4-0-0

### ISSUE THREAD

**Issue by ghost** [wg/wrk#283]
The current release is broken on Ubuntu;  It loops forever without issuing any requests.  Therefore, I am running 4-0-0

Issuing the following command "wrk http://192.168.1.5:8080/tools/time" will generate the following packet

000000  47 45 54 20 2f 74 6f 6f 6c 73 2f 74 69 6d 65 20   GET /tools/time 
000016  48 54 54 50 2f 31 2e 31 0d 0a 48 6f 73 74 3a 20   HTTP/1.1..Host: 
000032  31 39 32 2e 3a 38 30 38 30 2f 74 6f 6f 6c 73 2f   192.:8080/tools/
000048  74 69 0d 0a 0d 0a                                 ti....

The Host field includes "192.:8080/tools/ti" instead of "192.168.1.5:8080"

**Comment by wg** [comment]
Thanks, pretty sure this was fixed in a later version of wrk.
