### ISSUE TITLE
Command line not recognizing multiple GET parameters

### ISSUE THREAD

**Issue by fwermelinger** [wg/wrk#285]
I tried running a command like this:
`wrk -t1 -c1 -d10s http://localhost:8001/mysite/api/metadata/label?apikey=x&language=en`

But the request that arrives at my local apache server is: 
`http://localhost:8001/mysite/api/metadata/label?apikey=x`
It's missing the second parameter &language=en 

So the first parameter is added to the url but it looks like the & is cutting off the rest of the string. Is this intended behavior or should I use another syntax for GET parameters?

I installed and ran wrk through "Bash on Ubuntu on Windows".

**Comment by methane** [comment]
`&` has special meaning in bash.  Quote the URL.

**Comment by fwermelinger** [comment]
That was it. Thanks a lot for that lesson @methane :)
