### ISSUE TITLE
make: *** [obj/bytecode.o] Error 127

### ISSUE THREAD

**Issue by fuzuchang** [wg/wrk#286]
[Felix@iZ11jdd4exqZ wrk-master]$ make WITH_LUAJIT=/usr/local/luajit2 WITH_OPENSSL=/usr
make: Warning: File `Makefile' has modification time 13 s in the future
CC src/wrk.c
CC src/net.c
CC src/ssl.c
CC src/aprintf.c
CC src/stats.c
CC src/script.c
CC src/units.c
CC src/ae.c
CC src/zmalloc.c
src/zmalloc.c: In function ‘zmalloc_get_memory_size’:
src/zmalloc.c:426:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
CC src/http_parser.c
LUAJIT src/wrk.lua
/bin/sh: luajit: command not found
make: *** [obj/bytecode.o] Error 127

**Comment by viennadd** [comment]
Hi,

Our code scanner has also reported this place for a potential uninitialized return value. Seems the macro conditions might not be covering all cases in some of the Linux environments (Ubuntu 16.04 in our case).

![image](https://user-images.githubusercontent.com/3396288/28813066-46b48a78-76ca-11e7-9ad0-b100c451c1a5.png)

Regards,
Alex, SourceBrella Inc.

**Comment by wg** [comment]
Thanks @fuzuchang! I've finally gotten around to grabbing the latest zmalloc from redis, seems like it's fixed this issue.
