### ISSUE TITLE
What response should I make to make wrk happy

### ISSUE THREAD

**Issue by linghuazaii** [wg/wrk#287]
`wrk` stop work if my server responses
```
HTTP/1.1 200 OK
Server: nginx
```
and `wrk` keep working if my server responses
```
not a valid http response
```
but `wrk` doesn't calculate `request/second` in this situation.

**Comment by wg** [comment]
See section 3.3.3 of RFC 7230. You need to send a Content-Length, Transfer-Encoding, or close the connection.
