### ISSUE TITLE
I don't see params used as option

### ISSUE THREAD

**Issue by allen-hxn** [wg/wrk#292]
I need to benchmark a REST API that takes parameters as input. I wondering if there is a way to do it using wrk.
I don't see params used anywhere. Also grepping for params in wrk repo did not yield anything useful.
ep: http://127.0.0.1/api?xx=123&xx=123&xxx=234
`wrk -t2 -c5 -t5s http://127.0.0.1/api?xx=123&xx=123&xxx=234`
last wrk request http://127.0.0.1/api?xx=123 not http://127.0.0.1/api?xx=123&xx=123&xxx=234
Do i miss something?

**Comment by wg** [comment]
You probably need to put quotes around the URL because the ampersand character has special meaning to most unix shells.

**Comment by allen-hxn** [comment]
get it. thanks.
