### ISSUE TITLE
How to send requests to more than one endpoints at the same time

### ISSUE THREAD

**Issue by qapolya** [wg/wrk#299]
Hi, first of all, thanks for the great tool. 
Since i am very new to the scripting languages and i cannot find defined data if what i need can be achieved with wrk, i decided to write here.
I need to stress test my API, for which reason i need to send POST requests to **more than one endpoints at the same time**, for ex.
Endpoint one - https://MyWebsite.com/Endpoint1?Token=XXX
Endpoint two - https://MyWebsite.com/Endpoint2?Token=YYY
How can this be achieved with wrk?

At the moment i am able to send requests to one endpoint at a time, see example script:
The command in bash is: 
_wrk --script ./test2.lua --latency -d 1s -t 1 -c 1 https://MyWebsite.com/Endpoint1?Token=XXX_

The code in the script is:
_counter = 1; //this is used to generate different requestid for each request
request = function()
wrk.method = "POST";
counter = counter + 1;
wrk.body = "{\"xxx\":\"xxx\",\"xyz\":\"xyz\",\"zzz\":\"zzz\", \"zyd\":{\"zyd\":[]},\"zss\":\"zss\",\"zzzz\":{\"zzzzz\":\"g-zz\",\"g-zz\":\"zsd\",\"zsd\":{\"zsdd\":{\"zsdd\":\"zsdf\",\"zsdf\":\"zsdg\"}}},\"zsdg\":{\"id\":\"id" .. counter .."\",\"zas\":\"zas" .. counter .. "\",\"bbb\":1.00},\"nnn\":false,\"nnnnn\":\"nnnnn\"}";
wrk.headers["Content-Type"] = "application/json";
return wrk.format("POST")
end_

**Comment by wg** [comment]
Hi, you can include a path using `wrk.format`, e.g. `wrk.format("GET", "/Endpoint1")` and vary that path on each call to `request()`.
