### ISSUE TITLE
wrk hangs when executing any test

### ISSUE THREAD

**Issue by mercer** [wg/wrk#304]
Hello, wrk hangs for me. Steps to reproduce:

- install ubuntu 17.04
- install wrk using https://github.com/wg/wrk/wiki/Installing-wrk-on-Linux
- execute any time, for example `wrk -t1 -c10 -d10s https://google.com`
- wrk seems to finish the test, but process doesn't end, no report is printed
- I have to kill the process to make it stop

Please note that it worked fine for me on ubuntu 16.04

**Comment by ivanzamanov** [comment]
Hi, same here.
Some more info - seems to be specifically related to the current 17.04 package. Building from source works just fine.

**Comment by wg** [comment]
Thanks @ivanzamanov!
