### ISSUE TITLE
zmalloc.c:426 compilation warning

### ISSUE THREAD

**Issue by majek** [wg/wrk#309]
```
src/zmalloc.c: In function ‘zmalloc_get_memory_size’:
src/zmalloc.c:426:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
```

This is on vanilla ubuntu saucy, on x86-64.

**Comment by wg** [comment]
Thanks! zmalloc is borrowed from redis and I occasionally pull the latest version, so I'd suggest offering a PR to the redis repo: https://github.com/antirez/redis/blob/unstable/src/zmalloc.c.
