### ISSUE TITLE
fix for building with libressl

### ISSUE THREAD

**Issue by itoffshore** [wg/wrk#310]
When building `wrk 4.0.2` with `libressl` for [Alpine Linux](https://pkgs.alpinelinux.org/packages?name=wrk&branch=&repo=&arch=&maintainer=) I needed to build with the following:

```
cd "$builddir"
touch buildinf.h
make -j1 -C "$builddir"
```
building with `-j2` or more causes a race condition somewhere

**Comment by Jack-Kingdom** [comment]
Same problem faced when compile on Ubuntu. Error will be throw under parallel compilation.

**Comment by itoffshore** [comment]
closing as tidying up old issues

`libressl` seems to becoming dropped nowadays (e.g `opnsense`) - now that `openssl` has been improved
