### ISSUE TITLE
How can i install this tool on my Cnetos 7 ?

### ISSUE THREAD

**Issue by robinwangrubin** [wg/wrk#311]
When i clone this project, I have no idea to install it.  help~~

**Comment by jorge-matricali** [comment]
```
yum groupinstall "Development Tools"
yum install -y openssl-devel
yum install -y git
git clone https://github.com/wg/wrk.git
cd wrk
make
```
https://github.com/wg/wrk/wiki/Installing-Wrk-on-Linux

**Comment by wg** [comment]
Thank you @jorge-matricali!

**Comment by robinwangrubin** [comment]
@jorge-matricali  Thank you very much.

**Comment by andrei-polukhin** [comment]
@matricali We may have forgotten the last step: copying `wrk` to the PATH: `sudo cp wrk /usr/local/bin/`
