### ISSUE TITLE
Should include lua.h directly (not <luajit-2.0/lua.h>)

### ISSUE THREAD

**Issue by daurnimator** [wg/wrk#314]
Currently at https://github.com/wg/wrk/blob/91655b5520b524fc0b802ad12220c9dcd546757e/src/wrk.h#L13 luajit 2.0's header file is included directly:

```C
#include <luajit-2.0/lua.h>
```

However my machine(s) have luajit 2.1 installed (in which case I would need to include `<luajit-2.1/lua.h>`)

Instead I think you should include only `<lua.h>` and have it up to user to place luajit include directory early in search path

**Comment by myfreeweb** [comment]
Yeah, I also needed to change the old deprecated `luaL_reg` to `luaL_Reg` in `script.c` to make it build with luajit 2.1

**Comment by wg** [comment]
Good idea, thanks! I've done this, along with finally upgrading the bundled LuaJIT to 2.1.0-beta3 since it doesn't seem like a final release will be out anytime soon.

**Comment by myfreeweb** [comment]
Thanks for the update, are you going to make a release of wrk with this change soon?
