### ISSUE TITLE
[Support] Store in disk a report

### ISSUE THREAD

**Issue by jabrena** [wg/wrk#315]
Hi, I would like to store in disk the result from a WRK execution for an analysis of results later.

I saw in the folder the following example:
https://github.com/wg/wrk/blob/master/scripts/report.lua

I would like to know how to store in disk the result. The idea is to store in disk the results about latency and request with a specific format:

``` json
{
"latency":wrk.getLatency(),
"requests":wrk.getRequests()
}
```

Any help?

Many thanks in advance.

Juan Antonio

**Comment by wg** [comment]
Hey @jabrena, I suggest reading the I/O section of the Lua book, it describes how to do this. https://www.lua.org/pil/21.2.html
