### ISSUE TITLE
wrk gave less request number

### ISSUE THREAD

**Issue by wenchma** [wg/wrk#316]
hi,

 I used `wrk` to complete `1530 requests in 1.09s`, but I found my backend service received `2529` requests,   
it's strange, why the numbers are different ? 

I ran the following cmd:

```
wrk --timeout 1m -c 1000 -d 1 -t 20
```

**Comment by wg** [comment]
Hey @wenchma, wrk doesn't count requests that are in-flight when the benchmark ends. You've got a lot of connections going there and a very short duration so there'll likely be a lot of requests pending. wrk's request count output isn't meant to be comprehensive, it's just the number used for calculating statistics.
