### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by bhauer** [wg/wrk#32]
Understanding fully the significant undertaking this would represent, I am curious if SSL support is coming to Wrk in the future.  We would like to be able to include a new test that exercises SSL as part of our benchmark suite.

We briefly experimented with http-perf, which supports SSL, but its use case seems different from what we have in mind.

Thanks!

**Comment by suni1mp** [comment]
hi @bhauer , @wg ,  does wrk support to pass client certificate as part of the request like ".jks" or ".pem" file
example below:
its a https request and i need pass client cert file as show in curl statement:
curl --cert certificate_file.pem:password https://URL
