### ISSUE TITLE
Consider merging in wrk2 tree?

### ISSUE THREAD

**Issue by rbtcollins** [wg/wrk#323]
The wrk2 tree has some very interesting histogram improvements - and a bunch of related PR's against it as well. Would you be open to merging those in? And if so, what needs to happen to enable that? (e.g. is it just someone making a PR for you?).

**Comment by wg** [comment]
Hey @rbtcollins, the naming of "wrk2" is unfortunate, it's evolved into a very different tool based on generating load a constant rate and can only record latencies at millisecond granularity. Whereas wrk generates load as fast as possible and tracks latency at the microsecond level.

I think there's room for both sorts of load generators and I've learned a lot from Gil's work on accurate latency calculations. The runtime statistics calculations of wrk were rewritten and and greatly improved thanks to his input.

**Comment by rbtcollins** [comment]
Thanks @wg - I didn't realise that it couldn't handle sub ms granularity. Thanks for the explanation.
