### ISSUE TITLE
HTTP Request Signing

### ISSUE THREAD

**Issue by rex-remind101** [wg/wrk#325]
Every request I'm trying to use for load testing must follow [HTTP request signing](https://blog.andrewhoang.me/how-api-request-signing-works-and-how-to-implement-it-in-nodejs-2/) however I don't see a way to sign requests from wrk. Could this be added as a feature?

**Comment by wg** [comment]
@rex-remind101 I'd recommend you check out wrk's support for Lua scripts, it may be possible.

**Comment by rex-remind101** [comment]
So not added as a feature then?
