### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by fcambus** [wg/wrk#332]
It would be nice if you would consider adding proper source release tarballs,
as GitHub auto-generated tarballs are not immutable. This is an issue [1] for
operating systems creating packages for wrk. Thanks in advance.

[1] https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by tst2005** [comment]
like https://github.com/jgm/lunamark/issues/29 ?

**Comment by fcambus** [comment]
@tst2005 Yes, same issue. Basically, it would just be grabbing the auto-generated file and uploading it as a release asset, to ensure the file is immutable.

**Comment by fcambus** [comment]
@tst2005 As stated already, those auto-generated tarballs are not immutable.

**Comment by tst2005** [comment]
* what is change between 2 auto-generated tarballs ? timestamp ?
* why not improving our tool to generate a immutable archive from an auto-generated one ?
