### ISSUE TITLE
headers are not accepting in wrk.format

### ISSUE THREAD

**Issue by shaikshakeel** [wg/wrk#352]
Hi, 

I am trying to post data to API.  i am building request every time. and i am adding headers to wrk.format() method. headers are not accepting event though headers type is string. 

```
headers = {}
s = {}
request = function() 
 
 headers["Authorization"] = "key"
 for name, value in pairs(headers) do
      s[1] = string.format("%s: %s", name, value)
 end
 print(s[1])
 print(type(s[1])
 return wrk.format("POST", "/api/", s[1] ,data)
end
```

throwing error  : 
`PANIC: unprotected error in call to Lua API ([string "wrk"]:0: attempt to index field 'headers' (a string value))`

Can u help me with this ?

**Comment by wg** [comment]
Hi @shaikshakeel, headers needs to be a table not a string.
