### ISSUE TITLE
Add support for basic auth header by parsing input url

### ISSUE THREAD

**Issue by ghost** [wg/wrk#356]
Hi,

I searched source code for 2 phrases _"authorization"_ and _"basic"_. It seems current version `4.1.0` doesn't support parsing basic auth in url.

For example: `https://user:password@localhost`

May I ask if you could consider adding support for that?

Thank you,

**Comment by ignatiusd** [comment]
Hello,

You can pass -H command line parameter with value "authorization: Basic _<base64 encoded user:password>_"

Hope this helps.

**Comment by wg** [comment]
Thanks @ignatiusd!

**Comment by AlexanderMatveev** [comment]
@ignatiusd trying to send basic header with -H parameter, but it's not working:

```sh
wrk -t 1 -H "Authorization:Basic <base64-encoded-auth>" <url>
```

Curl with same header value works fine:

```sh
curl -H "Authorization:Basic <base64-encoded-auth>" <url>
```

**Comment by AlexanderMatveev** [comment]
It looks like space before "Basic" is required. But still works with curl and no space 😃
