### ISSUE TITLE
How to count non 200 responses

### ISSUE THREAD

**Issue by TimurNurlygayanov** [wg/wrk#363]
Hi, I want to check all the responses from server and make sure that all responses had 200 status code and some expected body.

I've tried lua script like this:

```
counter = 0
  
response = function(status, headers, body)
    if status == 200 and body == "Hello, world" then
        counter = counter + 1
    else
        print(status, body)
    end

    return wrk.format(counter)

end
```

and I'm executing it with the command:

`./wrk -t1 -c100 -d3s -s my_check.lua http://0.0.0.0:5000/`

so, it prints all "unexpected" responses, but I also want to make sure that incorrect responses will not included to statistics like requests/per second. 
How to do this?

**Comment by wg** [comment]
Hi @TimurNurlygayanov, this is not possible with wrk as it counts all valid responses regardless of their status code.
