### ISSUE TITLE
socket errors: connect errors

### ISSUE THREAD

**Issue by horizonzy** [wg/wrk#371]
when I use it as follow,it seems no problem:
wrk -t 12 -c 200 -d 30  destUrl.

but I change connection to 300.the connect error happen as follow:
wrk -t 12 -c 300 -d 30  destUrl.

 12 threads and 300 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    91.56ms   31.46ms 342.61ms   70.65%
    Req/Sec   223.39     40.76   464.00     80.14%
  78773 requests in 30.07s, 279.31MB read
  Socket errors: connect 252, read 0, write 0, timeout 0
Requests/sec:   2619.58
Transfer/sec:      9.29MB

is my client's port not enough or other reason?
any ideas?

**Comment by bayareabear** [comment]
I have the same problem:
xzhang3$ wrk -t 12 -c 400 -d 30s URL

  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    14.38ms    9.65ms 224.67ms   98.04%
    Req/Sec     1.45k     0.89k    3.67k    52.48%
  517458 requests in 30.10s, 110.05MB read
  Socket errors: connect 157, read 0, write 0, timeout 0
  Non-2xx or 3xx responses: 517458
Requests/sec:  17193.20
Transfer/sec:      3.66MB

**Comment by arjunbiswas21289** [comment]
same for me.. is there anything we have to do on Server level to fix.

**Comment by Icedroid** [comment]
I have the same issue:
`
wrk -t4 -c1000 -d30s -T30s --latency http://127.0.0.1:8082/v1/workload/filter
Running 30s test @ http://127.0.0.1:8082/v1/workload/filter
  4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   116.10ms   26.33ms 283.93ms   78.97%
    Req/Sec   516.91    118.49     0.92k    72.16%
  Latency Distribution
     50%  110.66ms
     75%  129.35ms
     90%  148.22ms
     99%  206.18ms
  61719 requests in 30.10s, 14.48MB read
  Socket errors: connect 751, read 37, write 0, timeout 0
Requests/sec:   2050.30
Transfer/sec:    492.55KB
`

**Comment by qianxi0617** [comment]
I have the same problem:


wrk -t4 -c1000 -d60s -s ./scripts/post.lua http://127.0.0.1:5077/VehiclePlateChartletApi
Running 1m test @ http://127.0.0.1:5077/VehiclePlateChartletApi
  4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   170.83ms  172.45ms   1.98s    94.19%
    Req/Sec    87.01     47.96   260.00     73.17%
  19509 requests in 1.00m, 3.57MB read
  Socket errors: connect 0, read 0, write 0, timeout 137
Requests/sec:    324.70
Transfer/sec:     60.90KB

**Comment by 8427003** [comment]
`ulimit -n` view and `ulimit -n 65535`setting your local machine max file num
