### ISSUE TITLE
 how to construct put requests using wrk? #67 

### ISSUE THREAD

**Issue by bayareabear** [wg/wrk#372]
I want to load testing put request with different files (10000 files locally). How do I construct put requests? The closest I found is POST.lua, but how do I construct PUT request to upload files?
Thank you!

**Comment by heyyyoyy** [comment]
@bayareabear try this https://github.com/playframework/prune/blob/master/src/main/resources/com/typesafe/play/prune/assets/wrk_upload.lua#L1-L36

**Comment by wg** [comment]
Thanks @heyyyoyy!
