### ISSUE TITLE
Add note about setting MACOSX_DEPLOYMENT_TARGET for Macos installation

### ISSUE THREAD

**Issue by koenpunt** [wg/wrk#373]
When running `make` (after making the changes to the `Makefile` mentioned in the wiki), I got the following output:

```
$ make
Building LuaJIT...
==== Building LuaJIT 2.1.0-beta3 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
HOSTLINK  host/minilua
ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [host/minilua] Error 1
make[1]: *** [src/luajit] Error 2
make: *** [obj/lib/libluajit-5.1.a] Error 2
```

After some searching, I found that this is due to luajit expecting the `MACOSX_DEPLOYMENT_TARGET` environment variable, and when it isn't set it uses `10.4`, which probably isn't the right version for anyone building wrk.

Thus the error can be resolved by setting `MACOSX_DEPLOYMENT_TARGET=10.14` (for Mojave) and running `make` again.

**Comment by futurechan** [comment]
It made quite a bit more progress for but still failed.
> LINK wrk
> Undefined symbols for architecture x86_64:
>   "_OPENSSL_init_crypto", referenced from:
>       _ssl_init in ssl.o
>   "_OPENSSL_init_ssl", referenced from:
>       _ssl_init in ssl.o
>   "_TLS_client_method", referenced from:
>       _ssl_init in ssl.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [wrk] Error 1

**Comment by koenpunt** [comment]
@futurechan have a look here: https://github.com/wg/wrk/blob/7594a95186ebdfa7cb35477a8a811f84e2a31b62/INSTALL#L11-L29

**Comment by wg** [comment]
Thanks @koenpunt! I've updated the Makefile to set this.
