### ISSUE TITLE
Ignore Cache-Control layer?

### ISSUE THREAD

**Issue by lukeed** [wg/wrk#380]
Hey there,

Is it possible to bypass HTTP caching? Didn't find any flags or previous issues that had to do with this. Sorry if I missed something relevant.

I want to benchmark production infrastructure throughout without changing the infrastructure itself, of course.

Ideally, `wrk` would disregard any `Cache-Control` headers, if possible, or it could send a `no-cache` in the request header, or randomize a querystring on the URL itself as a last resort.

This is probably doable via the Lua scripting, I realize, but that's a completely foreign world to me, hah

Thanks~!

**Comment by wg** [comment]
Hey @lukeed, you can use `-H "Cache-Control: ..."` to pass any header information you want without scripting, but yes if you want to make a random query string you'll need to write or find a script. wrk doesn't send any cache-related headers by default.

**Comment by lukeed** [comment]
Awesome, thank you. Didn't realize there were more flags available than what's listed on `--help`.

Thanks~!
