### ISSUE TITLE
zmalloc: Out of memory trying to allocate

### ISSUE THREAD

**Issue by suminb** [wg/wrk#40]
### Environment
- Ubuntu 13.04
- Linux kernel 3.8.0-26 (x86_64)
### Procedures

Here's what I did.

```
sudo apt-get install libcurl4-openssl-dev
make
./wrk ${URL}
```

Then I got the following error:

```
zmalloc: Out of memory trying to allocate 800000040 bytes
Aborted (core dumped)
```

I tried a number of different combinations of options (such as `-t`, `-c` and `-d`) but `wrk` produced the same error message regardless of what options were given.

**Comment by robertd** [comment]
+1

**Comment by methane** [comment]
Shorter timeout may save your memory.
https://github.com/wg/wrk/search?utf8=✓&q=stats_alloc&type=Code

**Comment by robertd** [comment]
ty

**Comment by methane** [comment]
https://github.com/wg/wrk/commit/39af03f7ba30333aed173db9833340278ac223b6
This commit reduced memory usage dramatically.

Before: 800MB * 2 for `statistics.latency` and `statistics.requests`
After: 8 * (timeout [us]) for `statistics.latency` and 80MB for `statistics.requests`
