### ISSUE TITLE
How can I run test with specific concurrent?

### ISSUE THREAD

**Issue by ALTELMA** [wg/wrk#403]
WRK is a good tool for test performance, but I still confusing about some options.

**Example:** I want to test our application can support 2,000 concurrent at the same time.
What is an option for this case?

Like this?
```wrk -t12 -c2000 -d1s http://127.0.0.1:8080/index.php```

I wondering about what is the right way to test our application to know concurrent support.

Anyone please suggest and help me :)

**Comment by graywolf** [comment]
Well directly from readme:

```
-c, --connections: total number of HTTP connections to keep open with
                   each thread handling N = connections/threads
```

...
