### ISSUE TITLE
Build fails on MacOS 10.15

### ISSUE THREAD

**Issue by sanderdekoning** [wg/wrk#422]
<img width="534" alt="Screenshot 2020-03-26 at 11 20 16" src="https://user-images.githubusercontent.com/43604043/77636035-c7023200-6f53-11ea-8fb3-2c999228bd92.png">

wrk cannot be build on MacOS 10.15, is there anything I can do to resolve this issue? Seems to be LuaJIT related

**Comment by NyanKiyoshi** [comment]
Idem 👍

**Comment by NyanKiyoshi** [comment]
This could be a possible fix https://github.com/Shopify/homebrew-shopify/pull/157 if we were to do: 
```makefile
ifeq (,$(findstring 10.15, $(MACOSX_DEPLOYMENT_TARGET)))
    ...
```

For now I'm trying to update xcode as it is the root of the issue.

**Comment by NyanKiyoshi** [comment]
Seems like it works now that I upgraded xcode to latest.

**Comment by wg** [comment]
Thank you @NyanKiyoshi!
