### ISSUE TITLE
Segfault when trying to build wrk

### ISSUE THREAD

**Issue by purplefox** [wg/wrk#427]
Hi I am trying to build wrk on MacOS Catalina 10.15.2 and it segfaults when trying to build luajit:

```
(base) Tim-Foxs-MBP15:wrk tfox$ make WITH_OPENSSL=/usr/local/opt/openssl
Building LuaJIT...
==== Building LuaJIT 2.1.0-beta3 ====
/Library/Developer/CommandLineTools/usr/bin/make -C src
BUILDVM   lj_folddef.h
make[2]: *** [lj_folddef.h] Segmentation fault: 11
make[2]: *** Deleting file `lj_folddef.h'
make[1]: *** [src/luajit] Error 2
make: *** [obj/lib/libluajit-5.1.a] Error 2
```

Any ideas how to get past this? I installed luajit freshly from homebrew and I have a fresh xcode developer tools install.

**Comment by javenwang** [comment]
try to `brew install luajit` and modify wrk's Makefile to use luajit we just installed. Hope this helpful.

**Comment by wg** [comment]
Perhaps this is the same issue as https://github.com/wg/wrk/issues/422 and fixed by a newer XCode?
