### ISSUE TITLE
zero stats with wrk

### ISSUE THREAD

**Issue by MrSiz** [wg/wrk#428]
HttpServer listens on port 12345.
![image](https://user-images.githubusercontent.com/11487926/82107717-6d043880-975c-11ea-842b-68205197ac5c.png)
When I used wrk testing, there was no request. But webbench worked well. And the HTTP response is as follows:
![image](https://user-images.githubusercontent.com/11487926/82107797-e9971700-975c-11ea-9fa2-e6bcb086b8b9.png)

**Comment by Fatahir** [comment]
set the duration almost greater than 30s
