### ISSUE TITLE
How to assert response code or body

### ISSUE THREAD

**Issue by MrPingPong** [wg/wrk#429]
How can i make a post request and assert the response code or body? Could you please help? Or may be share an example of lua script to use?

**Comment by swuecho** [comment]
https://github.com/wg/wrk/blob/master/scripts/post.lua

**Comment by MrPingPong** [comment]
Is there any way where we can assert the response and make the request as failed?
For example:
If the response code is not 200 then mark that particular request as failed.

**Comment by wg** [comment]
@MrPingPong you can write a custom reporting script that counts failures and outputs them in the final report.
