### ISSUE TITLE
not support 5.3 with redis-lua

### ISSUE THREAD

**Issue by bochuxt** [wg/wrk#432]
WRK2 only working with 5.1 lua + redis-lua + luasocket  

/usr/local/opt/lua@5.1

--  550  luarocks remove redis-lua
--  551  luarocks remove luasocket 

--  552  luarocks install  redis-lua --local --lua-dir=/usr/local/opt/lua@5.1
--  553  luarocks install  luasocket  --local --lua-dir=/usr/local/opt/lua@5.1
-- luarocks --lua-dir=/usr/local/opt/lua@5.1 install say

**Comment by wg** [comment]
This is not a forum for discussing wrk2 issues.
