### ISSUE TITLE
Unstable results for benchmarking

### ISSUE THREAD

**Issue by laith-leo** [wg/wrk#433]
Hi, 

I'm testing wrk locally on Nginx that is running on a Docker container locally on my MAC. The results of the same testing get me different results every time.

160 seconds | 90 seconds | 60 seconds | 30 seconds | 10 seconds

35.17ms         | 37.73ms       | 20.29ms     | 18.92ms      | 38.39ms
42.97ms      | 27.22ms      | 19.13ms      | 43.63ms      | 46.71ms
17.52ms      | 28.90ms      | 49.97ms      | 55.13ms      | 3.32ms
33.31ms      | 36.57ms      | 40.13ms      | 42.38ms      | 46.98ms
26.92ms      | 32.88ms      | 26.22ms      | 54.40ms      | 3.34ms
35.63ms      | 29.21ms      | 47.64ms      | 31.21ms      | 36.15ms

The command I used is:

`for i in {1..6}; do docker pause $(docker ps -q) && docker kill $(docker ps -q) && docker run -p 8000:80 -d nginx && sleep 5 && wrk -t10 -c10 -d160 http://127.0.0.1:8000/index.html --latency | grep Latency | head -n 1 | awk '{print $2}'; done`

Knowing that I have enabled 10 cores for Docker for testing.

I pretty much got the same non-stable output in my testing in an EC2 instance.

**Comment by wg** [comment]
Setting up a stable system for more reproducible results is a big topic and I don't think this is the proper forum for it. But to start you can look into disabling CPU frequency scaling in an EC2 instance so your CPU runs at a fixed rate regardless of load. I wouldn't expect much stability out of Docker for Mac which runs a full VM with a bunch of processes in addition to all the background processes on your Mac.
