### ISSUE TITLE
Unable to use openssl.cipher in LUA

### ISSUE THREAD

**Issue by Subtalime** [wg/wrk#437]
my code snippet:
    local cipher = require("openssl.cipher")
    c = cipher.new("AES-128-CBC")
Result:
bad argument #1 to 'new' (AES-128-CBC: invalid cipher type)

When I run this script with LuaJit (using luaopenssl), it works
Does WRK not support Cipher Names but rather needs the Key? If so, where can I find the keys?

**Comment by wg** [comment]
wrk's Lua environment does not include any libraries so this will be something specific to your environment that I cannot assist with.
