### ISSUE TITLE
Incorrect latency

### ISSUE THREAD

**Issue by chrisgleissner** [wg/wrk#438]
Hi,

I built wrk from source today and ran it on Ubuntu 18.04 against a locally started nginx, serving a static `index.html` from a Docker container, exposing it via a port mapping. 

I am getting latency results that don't seem to make sense.

Here some further details. I ran two tests - each with the same setting of a single connection, single thread and a one second test interval. Here are the results:

```chris@chris-VirtualBox:~/dev/tmp$ wrk -d 1 -c 1 -t 1 http://localhost:8000
Running 1s test @ http://localhost:8000
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.04ms   20.33ms 117.18ms   92.42%
    Req/Sec     5.07k     1.84k    6.70k    90.00%
  5047 requests in 1.00s, 3.34MB read
Requests/sec:   5043.27
Transfer/sec:      3.34MB

chris@chris-VirtualBox:~/dev/tmp$ wrk -d 1 -c 1 -t 1 http://localhost:8000
Running 1s test @ http://localhost:8000
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   487.51us    1.52ms  16.33ms   95.60%
    Req/Sec     5.03k     0.97k    6.15k    54.55%
  5504 requests in 1.10s, 3.65MB read
Requests/sec:   5006.85
Transfer/sec:      3.32MB
```

As you see, the first test reports a latency of 6.04ms with a total of 5043 requests served in the test interval. Meanwhile, the second test reports a latency of only 487us (so less than a tenth of test 1's latency), yet also claiming to have performed a total of 5504 requests.

This is impossible with a single thread and non-interleaving requests - ie. if we assume a request was only issued on receiving the response of the previous request, as was specified via the `-t 1` option. If the number of the requests served is roughly the same, so should be the request latency, given a single thread and connection.

Maybe I am misinterpreting these numbers. Your feedback is appreciated.

Thanks
Christian

**Comment by Subtalime** [comment]
Try WRK2 (somewhere here on GitHub)

**Comment by wg** [comment]
The latency numbers you're reporting are averages, which likely don't describe the actual distribution well, see https://www.infoq.com/interviews/tene-latency/ and try `--latency` to get a percentile breakdown.

**Comment by yujqiao** [comment]
Hi @wg I don't see how the distribution makes any differences here. The distribution matters when there are concurrent connections. But in the scenario, where there's only one thread and one connection at a time, the sum of latency is the duration of the test. And avg_latency = test_duration / n_ requsets. So the average latency is inversely proportional to the throughput.

**Comment by yujqiao** [comment]
I come across @moonming 's [article](https://zhuanlan.zhihu.com/p/43602062)(warning: in chinese) for this issue. Search `coordinated omission` in issues and it's a question that has been answered several times.
