### ISSUE TITLE
wrk mark 报错

### ISSUE THREAD

**Issue by XL-VII** [wg/wrk#440]
CC src/wrk.c
CC src/net.c
CC src/ssl.c
CC src/aprintf.c
CC src/stats.c
CC src/script.c
CC src/units.c
CC src/ae.c
CC src/zmalloc.c
CC src/http_parser.c
LUAJIT src/wrk.lua
/bin/sh: Fusion.app/Contents/Public: No such file or directory
make: *** [obj/bytecode.o] Error 127

请问一下是什么原因导致的

**Comment by wg** [comment]
See https://github.com/wg/wrk/pull/368.
