### ISSUE TITLE
can't increase RPS with more threads or more connections

### ISSUE THREAD

**Issue by liuzqt** [wg/wrk#442]
I have **Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz**

**try 1:**
firstly I run with `wrk -t4 -c500 -d30s`, and it gives me the result
```
Running 30s test @ http://localhost:5023/jsonrpc/internal.acquire_s3_read_lock
  4 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   129.92ms  389.76ms   5.46s    97.07%
    Req/Sec   251.85    102.04   515.00     70.43%
  Latency Distribution
     50%   64.03ms
     75%   76.02ms
     90%  104.03ms
     99%    2.14s 
  30046 requests in 30.04s, 5.28MB read
  Socket errors: connect 0, read 0, write 0, timeout 8
Requests/sec:   1000.17
Transfer/sec:    179.86KB
```

I got about 1000 RPS, and I want to increase the load. If I understand it correctly,  RPS increase is almost linear with connection number, maybe with some overhead.

**try 2:**
then I run `wrk -t4 -c1000 -d30s`, increasing connections from 500 to 1000, and I got

```
Running 30s test @ http://localhost:5023/jsonrpc/internal.acquire_s3_read_lock
  4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   109.84ms  313.49ms   5.50s    97.83%
    Req/Sec   252.22     88.41   464.00     62.46%
  Latency Distribution
     50%   64.02ms
     75%   76.05ms
     90%  107.98ms
     99%  928.02ms
  30060 requests in 30.05s, 5.28MB read
  Socket errors: connect 0, read 0, write 0, timeout 4
Requests/sec:   1000.30
Transfer/sec:    179.88KB
```
RPS is still 1000, I'm confused about this result. Here is my guess, connections are distributed to each thread, and inside one thread switching over connections has overhead, and 250 conn for one thread already max out its capacity considering the overhead, so 500conn to 1000conn didn't give me any higher RPS?

**try3:**
then I tried `wrk -t2 -c1000 -d30s`
If what I'm guessing above is true, reducing to 2 threads should almost cut the RPS to half, but I still got 1000RPS
```
Running 30s test @ http://localhost:5023/jsonrpc/internal.acquire_s3_read_lock
  2 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   108.70ms  345.66ms   9.91s    98.29%
    Req/Sec   534.52    137.42   808.00     62.04%
  Latency Distribution
     50%   63.99ms
     75%   75.95ms
     90%  100.05ms
     99%    1.08s 
  31838 requests in 30.05s, 5.59MB read
  Socket errors: connect 0, read 0, write 0, timeout 1
Requests/sec:   1059.55
Transfer/sec:    190.56KB
```

so it seems that each thread doesn't reach his max capacity?

So wrk has some internal cap for the rate or am I missing some parameter to tune this? I'm wondering if it's possible to generate like 10k RPS load with my machine

**Comment by wg** [comment]
Hi @liuzqt, I would suggest you start with 1 thread and 1 connection and then gradually raise the number of connections and threads until the client or server seems saturated. Benchmarking HTTP servers is more of an art than a science, there's a lot of moving parts and bottlenecks tend to be unique to a particular setup.

**Comment by liuzqt** [comment]
I tried to start with 1 thread and 1 connection, and increasing, when I reach about 90 connection with 1 thread, I got ~1.1k RPS.  After that, no matter how I increase connection or thread, RPS won't increase.

In my understanding, when RPS stop increase, either the server or the client side (the wrk) reach the bottleneck. In this case, obviously wrk did not reach its bottleneck yet, since I only give one thread. Then the server should reach its bottleneck, but this guess doesn't make sense, because if the server is saturated, then more load from wrk should result in high latency, but I didn't observe that.

Then it seems that neither the client nor server side reach its bottleneck? This conclusion sounds weird...

Actually, the reason I want to do benchmarking with my server is that, I observed significantly high latency with high request load in my production server. So I want to use wrk to somehow simulate that high load and figure out the bottleneck of my client.

**Comment by DuckRui** [comment]
> 我尝试从 1 个线程和 1 个连接开始，然后逐渐增加，当我用 1 个线程达到约 90 个连接时，我得到了 ~1.1k RPS。此后，无论我如何增加连接或线程，RPS 都不会增加。
> 
> 据我所知，当 RPS 停止增加时，服务器或客户端（wrk）都会达到瓶颈。在这种情况下，显然 wrk 尚未达到瓶颈，因为我只提供了一个线程。那么服务器应该会达到瓶颈，但这种猜测没有意义，因为如果服务器饱和，那么 wrk 的更多负载应该会导致高延迟，但我没有观察到这一点。
> 
> 那么看起来客户端和服务器端都没有达到瓶颈？这个结论听起来很奇怪......
> 
> 实际上，我想对我的服务器进行基准测试的原因是，我观察到生产服务器在高请求负载下延迟显著增加。因此，我想使用 wrk 以某种方式模拟这种高负载并找出客户端的瓶颈，因此我想尽可能多地为我的服务器创建负载，直到服务器饱和并且我可以观察到非常高的延迟。

Hi, I encountered the same problem to yours. Did you solve the problem later?
