### ISSUE TITLE
master branch compilation error 

### ISSUE THREAD

**Issue by cristigirbovan** [wg/wrk#443]
I tried to compile the source code and make it work under Windows 10 Cygwin (both x86 and 64), I receive the same error, please find the logs below.
Thanks a lot,
Cristi

>>>>>> error log <<<<<

CC src/wrk.c
src/wrk.c: In function ‘main’:
src/wrk.c:130:12: error: variable ‘sa’ has initializer but incomplete type
  130 |     struct sigaction sa = {
      |            ^~~~~~~~~
src/wrk.c:131:10: error: ‘struct sigaction’ has no member named ‘sa_handler’
  131 |         .sa_handler = handler,
      |          ^~~~~~~~~~
src/wrk.c:131:23: warning: excess elements in struct initializer
  131 |         .sa_handler = handler,
      |                       ^~~~~~~
src/wrk.c:131:23: note: (near initialization for ‘sa’)
src/wrk.c:132:10: error: ‘struct sigaction’ has no member named ‘sa_flags’
  132 |         .sa_flags   = 0,
      |          ^~~~~~~~
src/wrk.c:132:23: warning: excess elements in struct initializer
  132 |         .sa_flags   = 0,
      |                       ^
src/wrk.c:132:23: note: (near initialization for ‘sa’)
src/wrk.c:130:22: error: storage size of ‘sa’ isn’t known
  130 |     struct sigaction sa = {
      |                      ^~
src/wrk.c:134:5: warning: implicit declaration of function ‘sigfillset’ [-Wimplicit-function-declaration]
  134 |     sigfillset(&sa.sa_mask);
      |     ^~~~~~~~~~
src/wrk.c:135:5: warning: implicit declaration of function ‘sigaction’ [-Wimplicit-function-declaration]
  135 |     sigaction(SIGINT, &sa, NULL);
      |     ^~~~~~~~~
src/wrk.c:130:22: warning: unused variable ‘sa’ [-Wunused-variable]
  130 |     struct sigaction sa = {
      |                      ^~
src/wrk.c: In function ‘connect_socket’:
src/wrk.c:241:21: error: invalid use of undefined type ‘struct addrinfo’
  241 |     fd = socket(addr->ai_family, addr->ai_socktype, addr->ai_protocol);
      |                     ^~
src/wrk.c:241:38: error: invalid use of undefined type ‘struct addrinfo’
  241 |     fd = socket(addr->ai_family, addr->ai_socktype, addr->ai_protocol);
      |                                      ^~
src/wrk.c:241:57: error: invalid use of undefined type ‘struct addrinfo’
  241 |     fd = socket(addr->ai_family, addr->ai_socktype, addr->ai_protocol);
      |                                                         ^~
src/wrk.c:246:25: error: invalid use of undefined type ‘struct addrinfo’
  246 |     if (connect(fd, addr->ai_addr, addr->ai_addrlen) == -1) {
      |                         ^~
src/wrk.c:246:40: error: invalid use of undefined type ‘struct addrinfo’
  246 |     if (connect(fd, addr->ai_addr, addr->ai_addrlen) == -1) {
      |                                        ^~
In file included from src/main.h:4,
                 from src/wrk.c:5:
src/wrk.c: In function ‘print_units’:
src/wrk.c:554:20: warning: array subscript has type ‘char’ [-Wchar-subscripts]
  554 |     if (isalpha(msg[len-1])) pad--;
      |                 ~~~^~~~~~~
src/wrk.c:555:20: warning: array subscript has type ‘char’ [-Wchar-subscripts]
  555 |     if (isalpha(msg[len-2])) pad--;
      |                 ~~~^~~~~~~
make: *** [Makefile:72: obj/wrk.o] Error 1

**Comment by wg** [comment]
Hi @cristigirbovan, I wouldn't expect wrk to run under cygwin. You might try WSL since it seems to provide more of a full Unix environment.
