### ISSUE TITLE
Mac Install Error

### ISSUE THREAD

**Issue by Sunyelw** [wg/wrk#481]
Error
```
> brew install wrk
...
Error: The following formula cannot be installed from bottle and must be
built from source.
  openssl@1.1
Install the Command Line Tools:
  xcode-select --install
```

Mac OS Message
```
MacOS Monterey 12.0.1
```

Anything helps? thx.

**Comment by wg** [comment]
I've tagged wrk 4.2.0 which includes the relevant fixes for arm64 and hopefully should resolve any homebrew installation issues. However homebrew packaging is a 3rd party effort unrelated to this repository.
