### ISSUE TITLE
Create a 4.2.0 tag of the current HEAD to enable updates to homebrew

### ISSUE THREAD

**Issue by colinbendell** [wg/wrk#482]
Package managers like homebrew prefer to have a fixed release or tag to pull from and build the necessary binaries. The current 4.1 definition does not compile in Monterey or on M1s with homebrew but the current HEAD does. Tagging the head as 4.2 would allow us to simply update the homebrew formula.

**Comment by wg** [comment]
Thanks for the suggestion! A new release is a good idea, I've tagged 4.2.0.
