### ISSUE TITLE
one wrk can support max 65535 connections？

### ISSUE THREAD

**Issue by phygerr** [wg/wrk#493]
Can i exec this command?
wrk -t16 -c1000000...   In one vms？
The vm size is 8c16g
I need your help

**Comment by phygerr** [comment]
I guess i need ten vms to test 600000 connections，it's right？🧐

**Comment by stonejianbu** [comment]
Of course. A connection with a TCP port, but limited ports, so, as you know.

**Comment by phygerr** [comment]
您好，您发来的邮件我已经收到，我将及时对您的邮件做出回复！Hello, I have received your email, I will reply to your email in time.!                                                                 李飞_Phyger
