### ISSUE TITLE
Parameter for maximum request number per connection

### ISSUE THREAD

**Issue by wixyvir** [wg/wrk#51]
Do you plan to add this feature? I'd like to set the maximum number of requests per connection.
Thanks for your great tool !

**Comment by wg** [comment]
Hi, the [next](https://github.com/wg/wrk/tree/next) branch includes support for [stopping a thread](https://github.com/wg/wrk/blob/next/scripts/stop.lua) whenever you see fit, see details in [SCRIPTING](https://github.com/wg/wrk/blob/next/SCRIPTING).
