### ISSUE TITLE
Can I load test a https server with wrk?

### ISSUE THREAD

**Issue by Huixxi** [wg/wrk#511]
How can I carry a ca cert to verify the remote server when I send a request to a https server's domain name?
Just like curl --cacert xxx http://xxx

**Comment by axel22** [comment]
Did you find an answer for this? Is this possible?

**Comment by Huixxi** [comment]
> Did you find an answer for this? Is this possible?

Not possible, I turn to use k6, and set insecureSkipTLSVerify: true
