### ISSUE TITLE
Host header should have the full Host:port

### ISSUE THREAD

**Issue by ugorji** [wg/wrk#53]
My server uses the Host:port to decide who to serve a request.

wrk sends a Host header with only the host, leaving out the port.

This causes my server to respond with an error, as it cannot 
recognize a server based on just that host alone.

It's a one-line fix. Pull Request coming.

**Comment by whit537** [comment]
Ftr, the fix is in https://github.com/wg/wrk/commit/2a4b64033a11a30bbb98d70e9c7e52c4161c60e3.
