### ISSUE TITLE
Add --pipeline option back as a shortcut

### ISSUE THREAD

**Issue by trustin** [wg/wrk#59]
I find the `--pipeline` option useful when testing the raw performance of my HTTP server.  Could we resurrect the `--pipeline` option and make it a mere shortcut to:

```
--script TMPFILE
```

where `TMPFILE` is something like the following:

``` lua
init = function(args)
   wrk.init(args)

   local r = {}
   for i=1,pipeline_length do
      r[i] = wrk.format(...)
   end
   req = table.concat(r)
end

request = function()
   return req
end
```

If you like this idea, I can come up with a pull request.

P.S: When would the `pipeline` branch be merged?

**Comment by purplefox** [comment]
Folks,

Do you have a complete example of a pipelining script that takes depth as argument?

I tried to piece one together from the information on this thread but failed.

**Comment by purplefox** [comment]
OK I worked it out.

For the benefit of anyone else needing this. Here's a coimplete working script with parameterized depth:

```
init = function(args)

   depth = tonumber(args[1]) or 1

   local r = {}
   for i=1,depth do
      r[i] = wrk.format(nil, "/")
   end
   req = table.concat(r)
end

request = function()
   return req
end
```

**Comment by cheers00** [comment]
wondering if the following script also works. Only difference is at wrk.format

```
init = function(args)
  wrk.init(args)
  local r = {}
  local depth = tonumber(args[1]) or 1
  for i=1,depth do
    r[i] = wrk.format()
  end
  req = table.concat(r)
end
request = function()
  return req
end
```
