### ISSUE TITLE
wrk reports means and standard deviations but most web services latencies are not along a bell curve

### ISSUE THREAD

**Issue by jmhodges** [wg/wrk#64]
wrk reports averages and standard deviations, and by doing so, assumes that the latencies of a web service fall along a normal distribution. However, almost no web services do so.

Excluding those, and replacing them with the 50th and either 95th or 99.9th percentile would be more helpful for the vast majority of uses. Means and standard deviations of distributions that are not normal end up misleading more people about how their system behaves.

**Comment by ericandrewlewis** [comment]
Would it be worth to add `--latency` to the basic usage? Or add another example in the README?
