### ISSUE TITLE
Makefile fix 'undefined reference to ...' for errors

### ISSUE THREAD

**Issue by FrankRuben** [wg/wrk#81]
Hi wrk team,
compiling (Ubuntu 12.04; GNU Make 3.81; gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3) with a simple make and the project's Makefile leads to a compilation with many errors as mentioned in the subject. Changing the sequence of the SSL libraries to ```-lssl -lcrypto``` when defining LIBS in line 2 of the Makefile helped (for me).
Thanks for this very cool project, Frank

**Comment by wg** [comment]
Thanks for the bug report @FrankRuben! I've fixed this along with refactoring dependency management in wrk 4.0.2
