### ISSUE TITLE
fails to parse command line opts on aarch64

### ISSUE THREAD

**Issue by thresheek** [wg/wrk#87]
first of all, since aarch64 is not supported in luajit, I've compiled 2.0.0, but it wouldnt launch due to an error in parse_args function of src/wrk.c.

the following patch against 2.0.0 fixes the problem for me:
```
diff --git a/src/wrk.c b/src/wrk.c
index 09cb007..21a47b5 100644
--- a/src/wrk.c
+++ b/src/wrk.c
@@ -435,7 +435,8 @@ static struct option longopts[] = {
 };

 static int parse_args(struct config *cfg, char **url, char **headers, int argc, char **argv) {
-    char c, **header = headers;
+    char **header = headers;
+    int c;

     memset(cfg, 0, sizeof(struct config));
     cfg->threads     = 2;
```

this happens because apparently char is signed on that platform. I'm on arm64 machine running ubuntu 14.04. 

UPD: actually it should also happen on armv7/linux as well.

**Comment by wg** [comment]
Thank you, getopt_long returns an int so using a char was a mistake. I've pushed a commit to fix that.
