### ISSUE TITLE
Add documentation on relation between threads and connections

### ISSUE THREAD

**Issue by johnny** [wg/wrk#90]
I am trying to find out if the connections are shared between the threads or if each thread has a fixed percentile of the connections.
And if they are shared, how?

This would be great to have in the Wiki or Readme.

Thanks
Jonas

**Comment by AlekSi** [comment]
Hey, can we reopen it? This issue is not really a documentation. :) Small README addition would be useful.

**Comment by cheers00** [comment]
So, at any point of time, number of active connections is equal to number of threads. Right?
Or can one thread have more than one active connection?

**Comment by roysG** [comment]
How can i calculate the ration between the threads and connections, if i want to emulate 2000 users at the same time call the same url ?

**Comment by knasim** [comment]
i agree - the usage function should be updated to reflect in the documentation that the number of connections are divided among all the the threads. 

currently it states:  `-c, --connections <N>  Connections to keep open`
when can be misleading
