### ISSUE TITLE
Add way to allow throughput graphing

### ISSUE THREAD

**Issue by johnny** [wg/wrk#92]
Hi,

for an http interface that uniquely identifies clients, I need to graph the throughput. That is, I want to measure the throughput not only at the end of the load test, but also in between.
So far I have not found a way to do this with wrk master.

I think there are two options to solve this:
1. Run wrk repeatedly with shorter durations and use the same client id's on each run
2. Run wrk once, but react to SIGINFO (ctrl-t) or similar which causes wrk to report the current throughput and to reset the stats

I tried to use option 1. The main problem there is that threads in the lua interface have no id. Hence I could not preset the values for each thread (using env variables or similar).
To work around that, I generated unique ids and used that to request client ids from a local web server (`os.popen("curl localhost:9000/" .. unique_id)`). This approach sometimes worked, but most of the time it didn't with no indication why. Wrk just died.

I am willing to write a PR for that and just wanted to know which approach you would prefer, if at all.
(For option 1 I could reuse part of #74, which exposes a threat id)
Personally, I would prefer option 2.

**Comment by wg** [comment]
Hi, #74 some inspiration for a more general approach which I’ve taken in the [next](https://github.com/wg/wrk/tree/next) branch. In that branch I’ve added support for [setting and getting global variables](https://github.com/wg/wrk/blob/next/scripts/setup.lua) in a thread’s scripting environment.

The next branch will eventually become wrk 4.0. Until it does there's no stability promise but I'm very interested in your feedback and whether this addresses your needs. Thanks!

**Comment by johnny** [comment]
This looks very good. I love it when a tool gets even more hackable.

In my case, I guess my problem can be solved by creating some sort of timer, that calls a function similar to the `done` method in the setup.lua example in a regular interval. How would I go about that?
1. Executing a function at a regular interval seems to be missing. http://stackoverflow.com/questions/11926440/asynchronous-delay-in-lua-like-javascript-settimeout
2. Intercepting signals from my lua script has no obvious solution.

Perhaps you could add support to setup timed functions?
