### ISSUE TITLE
Lua script to match request/response

### ISSUE THREAD

**Issue by gitai** [wg/wrk#97]
I'm trying to figure out an efficient way to run a test which ensures that what I receive is what I sent.

Here is what I have so far:

-- globals are actually thread local storage            
counter = 0
matched_req = 0
req_set = {}

request = function()
   counter = counter + 1
   req_set[tostring(counter)] = true
   return wrk.format("POST",nil, nil, counter)
end

response = function(status, header, body)
    if req_set[body] then
        matched_req = matched_req + 1
    end
end

done = function(summary, latency, requests)
   io.write("\n-------------------------\n")
   io.write("Matched requests: " .. tostring(matched_req))
   io.write("\n-------------------------\n")
end  

How can I combine all thread local matched_req in done ?

10x

p.s 

This is my first lua script .. improvements welcome :)

**Comment by wg** [comment]
Hi @gitai, as you point out there's currently no built-in method of communication between each thread's Lua context. Perhaps there's a reasonable way to access shared memory via a Lua API, but that's outside the scope of wrk.
