### ISSUE TITLE
percentiles prudently reported for SUT freeze test

### ISSUE THREAD

**Issue by ceeaspb** [wg/wrk#99]
if I run wrk against against a system that responds in around 0.5-1ms with the following command line:

```
wrk --latency -d 10s -t 1 -c 1 <url>
```

And during that 10 seconds I freeze the SUT for 5 seconds (ie. 50% of the test time).

```
kill -TSTP 3344;sleep 5;kill -CONT 3344
```

I think I should get:
the 50th and 75th percentiles should report around 1ms and 2500ms respectively.

I get the following

```
$ wrk --latency -d 10s -t 1 -c 1 "<url>"
Running 10s test @ <url>
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.53s     2.50s    5.01s    50.61%
    Req/Sec   758.37    771.79     1.78k    74.48%
  Latency Distribution
     50%    5.01s 
     75%    5.01s 
     90%    5.01s 
     99%    5.01s 
  7264 requests in 10.00s, 2.58MB read
  Socket errors: connect 0, read 0, write 0, timeout 2
Requests/sec:    726.37
Transfer/sec:    263.88KB
```

which appears to be wrong. I may be running the wrong wrk command line though.
this could be a serious issue for anyone reporting percentiles from this tool.

**Comment by wg** [comment]
I've completely rewritten the way stats are handled in the 'next' branch, which eliminates sampling in favor of recording the latency for every request except those that exceed the timeout limit. The CO correction has also been improved to assign linearly increasing values between the actual latency and the expected interval between requests.
